///*
// * This file was automatically generated by EvoSuite
// * Mon Jul 13 16:30:08 GMT 2026
// */
//
//package org.apache.storm.daemon.drpc_4.another.evosuite;
//
//import org.apache.storm.daemon.drpc.BlockingOutstandingRequest;
//import org.apache.storm.daemon.drpc.DRPC;
//import org.apache.storm.daemon.drpc.RequestFactory;
//import org.apache.storm.generated.DRPCExecutionException;
//import org.apache.storm.metric.StormMetricsRegistry;
//import org.apache.storm.security.auth.IAuthorizer;
//import org.apache.storm.security.auth.ReqContext;
//import org.apache.storm.security.auth.authorizer.DenyAuthorizer;
//import org.apache.storm.security.auth.authorizer.NoopAuthorizer;
//import org.apache.storm.security.auth.authorizer.SimpleWhitelistAuthorizer;
//import org.apache.storm.security.auth.authorizer.SupervisorSimpleACLAuthorizer;
//import org.evosuite.runtime.EvoRunner;
//import org.evosuite.runtime.EvoRunnerParameters;
//import org.junit.Test;
//import org.junit.runner.RunWith;
//
//import javax.security.auth.Subject;
//import java.util.HashMap;
//import java.util.Hashtable;
//import java.util.Map;
//import java.util.concurrent.Future;
//import java.util.concurrent.TimeUnit;
//
//import static org.evosuite.runtime.EvoAssertions.*;
//import static org.junit.Assert.assertEquals;
//import static org.junit.Assert.fail;
//
//@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true)
//public class DRPC_ESTest extends DRPC_ESTest_scaffolding {
//
//  @Test(timeout = 4000)
//  public void test00()  throws Throwable  {
//      Subject subject0 = new Subject();
//      ReqContext reqContext0 = new ReqContext(subject0);
//      SimpleWhitelistAuthorizer simpleWhitelistAuthorizer0 = new SimpleWhitelistAuthorizer();
//      try {
//        DRPC.checkAuthorization(reqContext0, simpleWhitelistAuthorizer0, "{^Y3>7", "a/UimM+@%jT$^U1M");
//        fail("Expecting exception: Exception");
//
//      } catch(Exception e) {
//         //
//         // DRPC request denied for principal 'unknown', operation '{^Y3>7' and function 'a/UimM+@%jT$^U1M'
//         //
//         verifyException("org.apache.storm.daemon.drpc.DRPC", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test01()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      DRPC dRPC0 = new DRPC(stormMetricsRegistry0, (IAuthorizer) null, 600000L);
//      dRPC0.returnResult("", "org.apache.storm.generated.Supervisor$sendSupervisorAssignments_args$sendSupervisorAssignments_argsStandardSchemeFactory");
//  }
//
//  @Test(timeout = 4000)
//  public void test02()  throws Throwable  {
//    Future<?> future = executor.submit(new Runnable(){
//            @Override public void run() {
//        try {
//          StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//          DRPC dRPC0 = new DRPC(stormMetricsRegistry0, (IAuthorizer) null, 600000L);
//          // Undeclared exception!
//          try {
//            dRPC0.executeBlocking("org.apache.storm.generated.Supervisor$sendSupervisorAssignments_args$sendSupervisorAssignments_argsStandardSchemeFactory", "");
//            fail("Expecting exception: SecurityException");
//
//          } catch(SecurityException e) {
//             //
//             // Security manager blocks (\"javax.security.auth.AuthPermission\" \"getSubject\")
//             // java.lang.Thread.getStackTrace(Thread.java:1564)
//             // org.evosuite.runtime.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:434)
//             // javax.security.auth.Subject.getSubject(Subject.java:287)
//             // org.apache.storm.security.auth.ReqContext.<init>(ReqContext.java:51)
//             // org.apache.storm.security.auth.ReqContext.lambda$static$0(ReqContext.java:42)
//             // java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
//             // java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
//             // java.lang.ThreadLocal.get(ThreadLocal.java:172)
//             // org.apache.storm.security.auth.ReqContext.context(ReqContext.java:78)
//             // org.apache.storm.daemon.drpc.DRPC.execute(DRPC.java:133)
//             // org.apache.storm.daemon.drpc.DRPC.executeBlocking(DRPC.java:147)
//             // sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
//             // sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
//             // sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
//             // java.lang.reflect.Method.invoke(Method.java:498)
//             // org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:257)
//             // org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169)
//             // org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:220)
//             // org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307)
//             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213)
//             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55)
//             // java.util.concurrent.FutureTask.run(FutureTask.java:266)
//             // java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
//             // java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
//             // java.lang.Thread.run(Thread.java:750)
//             //
//             verifyException("org.evosuite.runtime.sandbox.MSecurityManager", e);
//          }
//        } catch(Throwable t) {
//            // Need to catch declared exceptions
//        }
//      }
//    });
//    future.get(4000, TimeUnit.MILLISECONDS);
//  }
//
//  @Test(timeout = 4000)
//  public void test03()  throws Throwable  {
//    Future<?> future = executor.submit(new Runnable(){
//            @Override public void run() {
//        try {
//          StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//          SimpleWhitelistAuthorizer simpleWhitelistAuthorizer0 = new SimpleWhitelistAuthorizer();
//          DRPC dRPC0 = new DRPC(stormMetricsRegistry0, simpleWhitelistAuthorizer0, 1294L);
//          // Undeclared exception!
//          try {
//            dRPC0.fetchRequest("storm.auth.simple-white-list.users");
//            fail("Expecting exception: SecurityException");
//
//          } catch(SecurityException e) {
//             //
//             // Security manager blocks (\"javax.security.auth.AuthPermission\" \"getSubject\")
//             // java.lang.Thread.getStackTrace(Thread.java:1564)
//             // org.evosuite.runtime.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:434)
//             // javax.security.auth.Subject.getSubject(Subject.java:287)
//             // org.apache.storm.security.auth.ReqContext.<init>(ReqContext.java:51)
//             // org.apache.storm.security.auth.ReqContext.lambda$static$0(ReqContext.java:42)
//             // java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
//             // java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
//             // java.lang.ThreadLocal.get(ThreadLocal.java:172)
//             // org.apache.storm.security.auth.ReqContext.context(ReqContext.java:78)
//             // org.apache.storm.daemon.drpc.DRPC.fetchRequest(DRPC.java:157)
//             // sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
//             // sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
//             // sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
//             // java.lang.reflect.Method.invoke(Method.java:498)
//             // org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:257)
//             // org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169)
//             // org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:220)
//             // org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307)
//             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213)
//             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55)
//             // java.util.concurrent.FutureTask.run(FutureTask.java:266)
//             // java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
//             // java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
//             // java.lang.Thread.run(Thread.java:750)
//             //
//             verifyException("org.evosuite.runtime.sandbox.MSecurityManager", e);
//          }
//        } catch(Throwable t) {
//            // Need to catch declared exceptions
//        }
//      }
//    });
//    future.get(4000, TimeUnit.MILLISECONDS);
//  }
//
//  @Test(timeout = 4000)
//  public void test04()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      SupervisorSimpleACLAuthorizer supervisorSimpleACLAuthorizer0 = new SupervisorSimpleACLAuthorizer();
//      DRPC dRPC0 = new DRPC(stormMetricsRegistry0, supervisorSimpleACLAuthorizer0, 1000L);
//      DRPCExecutionException dRPCExecutionException0 = new DRPCExecutionException();
//      // Undeclared exception!
//      try {
//        dRPC0.failRequest((String) null, dRPCExecutionException0);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test05()  throws Throwable  {
//      SimpleWhitelistAuthorizer simpleWhitelistAuthorizer0 = new SimpleWhitelistAuthorizer();
//      DRPC dRPC0 = null;
//      try {
//        dRPC0 = new DRPC((StormMetricsRegistry) null, simpleWhitelistAuthorizer0, 128L);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.storm.daemon.drpc.DRPC", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test06()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      DenyAuthorizer denyAuthorizer0 = new DenyAuthorizer();
//      DRPC dRPC0 = null;
//      try {
//        dRPC0 = new DRPC(stormMetricsRegistry0, denyAuthorizer0, (-1013L));
//        fail("Expecting exception: IllegalArgumentException");
//
//      } catch(IllegalArgumentException e) {
//         //
//         // Negative delay.
//         //
//         verifyException("java.util.Timer", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test07()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      stormMetricsRegistry0.registerTimer("drpc:num-result-calls");
//      DRPC dRPC0 = null;
//      try {
//        dRPC0 = new DRPC(stormMetricsRegistry0, (IAuthorizer) null, (-2114L));
//        fail("Expecting exception: IllegalArgumentException");
//
//      } catch(IllegalArgumentException e) {
//         //
//         // drpc:num-result-calls is already used for a different type of metric
//         //
//         verifyException("com.codahale.metrics.MetricRegistry", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test08()  throws Throwable  {
//      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
//      hashMap0.put("drpc.request.timeout.secs", "drpc.request.timeout.secs");
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      DRPC dRPC0 = null;
//      try {
//        dRPC0 = new DRPC(stormMetricsRegistry0, hashMap0);
//        fail("Expecting exception: NumberFormatException");
//
//      } catch(NumberFormatException e) {
//         //
//         // For input string: \"drpc.request.timeout.secs\"
//         //
//         verifyException("java.lang.NumberFormatException", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test09()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      DRPC dRPC0 = null;
//      try {
//        dRPC0 = new DRPC(stormMetricsRegistry0, (Map<String, Object>) null);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.storm.daemon.drpc.DRPC", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test10()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      Hashtable<String, Object> hashtable0 = new Hashtable<String, Object>();
//      hashtable0.put("drpc.authorizer", stormMetricsRegistry0);
//      DRPC dRPC0 = null;
//      try {
//        dRPC0 = new DRPC(stormMetricsRegistry0, hashtable0);
//        fail("Expecting exception: ClassCastException");
//
//      } catch(ClassCastException e) {
//         //
//         // org.apache.storm.metric.StormMetricsRegistry cannot be cast to java.lang.String
//         //
//         verifyException("org.apache.storm.daemon.drpc.DRPC", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test11()  throws Throwable  {
//    Future<?> future = executor.submit(new Runnable(){
//            @Override public void run() {
//        try {
//          StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//          SimpleWhitelistAuthorizer simpleWhitelistAuthorizer0 = new SimpleWhitelistAuthorizer();
//          DRPC dRPC0 = new DRPC(stormMetricsRegistry0, simpleWhitelistAuthorizer0, 4096L);
//          RequestFactory<BlockingOutstandingRequest> requestFactory0 = BlockingOutstandingRequest.FACTORY;
//          // Undeclared exception!
//          try {
//            dRPC0.execute("drpc.request.timeout.secs", "storm.auth.simple-white-list.users", requestFactory0);
//            fail("Expecting exception: SecurityException");
//
//          } catch(SecurityException e) {
//             //
//             // Security manager blocks (\"javax.security.auth.AuthPermission\" \"getSubject\")
//             // java.lang.Thread.getStackTrace(Thread.java:1564)
//             // org.evosuite.runtime.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:434)
//             // javax.security.auth.Subject.getSubject(Subject.java:287)
//             // org.apache.storm.security.auth.ReqContext.<init>(ReqContext.java:51)
//             // org.apache.storm.security.auth.ReqContext.lambda$static$0(ReqContext.java:42)
//             // java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
//             // java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
//             // java.lang.ThreadLocal.get(ThreadLocal.java:172)
//             // org.apache.storm.security.auth.ReqContext.context(ReqContext.java:78)
//             // org.apache.storm.daemon.drpc.DRPC.execute(DRPC.java:133)
//             // sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
//             // sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
//             // sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
//             // java.lang.reflect.Method.invoke(Method.java:498)
//             // org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:257)
//             // org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169)
//             // org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:220)
//             // org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307)
//             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213)
//             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55)
//             // java.util.concurrent.FutureTask.run(FutureTask.java:266)
//             // java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
//             // java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
//             // java.lang.Thread.run(Thread.java:750)
//             //
//             verifyException("org.evosuite.runtime.sandbox.MSecurityManager", e);
//          }
//        } catch(Throwable t) {
//            // Need to catch declared exceptions
//        }
//      }
//    });
//    future.get(4000, TimeUnit.MILLISECONDS);
//  }
//
//  @Test(timeout = 4000)
//  public void test12()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      SimpleWhitelistAuthorizer simpleWhitelistAuthorizer0 = new SimpleWhitelistAuthorizer();
//      DRPC dRPC0 = new DRPC(stormMetricsRegistry0, simpleWhitelistAuthorizer0, 1294L);
//      dRPC0.close();
//  }
//
//  @Test(timeout = 4000)
//  public void test13()  throws Throwable  {
//      Subject subject0 = new Subject();
//      ReqContext reqContext0 = new ReqContext(subject0);
//      NoopAuthorizer noopAuthorizer0 = new NoopAuthorizer();
//      DRPC.checkAuthorization(reqContext0, noopAuthorizer0, "", "");
//      //  // Unstable assertion: assertEquals(3, reqContext0.requestID());
//  }
//
//  @Test(timeout = 4000)
//  public void test14()  throws Throwable  {
//      DenyAuthorizer denyAuthorizer0 = new DenyAuthorizer();
//      // Undeclared exception!
//      try {
//        DRPC.checkAuthorization((ReqContext) null, denyAuthorizer0, "4zPa", "4zPa");
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.storm.daemon.drpc.DRPC", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test15()  throws Throwable  {
//      Subject subject0 = new Subject();
//      ReqContext reqContext0 = new ReqContext(subject0);
//      DRPC.checkAuthorization(reqContext0, (IAuthorizer) null, "", "");
//      assertEquals(1, reqContext0.requestID());
//  }
//
//  @Test(timeout = 4000)
//  public void test16()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      NoopAuthorizer noopAuthorizer0 = new NoopAuthorizer();
//      DRPC dRPC0 = new DRPC(stormMetricsRegistry0, noopAuthorizer0, 1003L);
//      dRPC0.failRequest(":wuT,H#h`}:R\"LChi/", (DRPCExecutionException) null);
//  }
//
//  @Test(timeout = 4000)
//  public void test17()  throws Throwable  {
//      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
//      hashMap0.put("drpc.authorizer", "drpc.authorizer");
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      DRPC dRPC0 = null;
//      try {
//        dRPC0 = new DRPC(stormMetricsRegistry0, hashMap0);
//        fail("Expecting exception: IllegalStateException");
//
//      } catch(IllegalStateException e) {
//         //
//         // Unable to instantiate DRPC authorizer drpc.authorizer
//         //
//         verifyException("org.apache.storm.daemon.drpc.DRPC", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test18()  throws Throwable  {
//      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      DRPC dRPC0 = null;
//      try {
//        dRPC0 = new DRPC(stormMetricsRegistry0, hashMap0);
//        fail("Expecting exception: IllegalArgumentException");
//
//      } catch(IllegalArgumentException e) {
//         //
//         // Don't know how to convert null to int
//         //
//         verifyException("org.apache.storm.utils.ObjectReader", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test19()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      DRPC dRPC0 = new DRPC(stormMetricsRegistry0, (IAuthorizer) null, 1L);
//      // Undeclared exception!
//      try {
//        dRPC0.returnResult((String) null, (String) null);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//      }
//  }
//}
