///*
// * This file was automatically generated by EvoSuite
// * Mon Jul 13 15:58:19 GMT 2026
// */
//
//package org.apache.storm.daemon.drpc_1.another.evosuite;
//
//import org.apache.storm.daemon.drpc.BlockingOutstandingRequest;
//import org.apache.storm.daemon.drpc.DRPC;
//import org.apache.storm.daemon.drpc.RequestFactory;
//import org.apache.storm.generated.DRPCExecutionException;
//import org.apache.storm.metric.StormMetricsRegistry;
//import org.apache.storm.security.auth.IAuthorizer;
//import org.apache.storm.security.auth.ReqContext;
//import org.apache.storm.security.auth.authorizer.*;
//import org.evosuite.runtime.EvoRunner;
//import org.evosuite.runtime.EvoRunnerParameters;
//import org.junit.Test;
//import org.junit.runner.RunWith;
//
//import javax.management.remote.JMXPrincipal;
//import javax.security.auth.Subject;
//import java.util.HashMap;
//import java.util.HashSet;
//import java.util.Map;
//import java.util.concurrent.Future;
//import java.util.concurrent.TimeUnit;
//
//import static org.evosuite.runtime.EvoAssertions.*;
//import static org.junit.Assert.*;
//
//@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true)
//public class DRPC_ESTest extends DRPC_ESTest_scaffolding {
//
//  @Test(timeout = 4000)
//  public void test00()  throws Throwable  {
//    Future<?> future = executor.submit(new Runnable(){
//            @Override public void run() {
//        try {
//          StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//          SimpleWhitelistAuthorizer simpleWhitelistAuthorizer0 = new SimpleWhitelistAuthorizer();
//          DRPC dRPC0 = new DRPC(stormMetricsRegistry0, simpleWhitelistAuthorizer0, 1845L);
//          // Undeclared exception!
//          try {
//            dRPC0.executeBlocking("storm.auth.simple-white-list.users", (String) null);
//            fail("Expecting exception: SecurityException");
//
//          } catch(SecurityException e) {
//             //
//             // Security manager blocks (\"javax.security.auth.AuthPermission\" \"getSubject\")
//             // java.lang.Thread.getStackTrace(Thread.java:1564)
//             // org.evosuite.runtime.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:434)
//             // javax.security.auth.Subject.getSubject(Subject.java:287)
//             // org.apache.storm.security.auth.ReqContext.<init>(ReqContext.java:51)
//             // org.apache.storm.security.auth.ReqContext.lambda$static$0(ReqContext.java:42)
//             // java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
//             // java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
//             // java.lang.ThreadLocal.get(ThreadLocal.java:172)
//             // org.apache.storm.security.auth.ReqContext.context(ReqContext.java:78)
//             // org.apache.storm.daemon.drpc.DRPC$AuthorizationSupport.checkCurrent(DRPC.java:187)
//             // org.apache.storm.daemon.drpc.DRPC$AuthorizationSupport.access$800(DRPC.java:164)
//             // org.apache.storm.daemon.drpc.DRPC.execute(DRPC.java:138)
//             // org.apache.storm.daemon.drpc.DRPC.executeBlocking(DRPC.java:149)
//             // sun.reflect.GeneratedMethodAccessor206.invoke(Unknown Source)
//             // sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
//             // java.lang.reflect.Method.invoke(Method.java:498)
//             // org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:257)
//             // org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169)
//             // org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:220)
//             // org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307)
//             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213)
//             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55)
//             // java.util.concurrent.FutureTask.run(FutureTask.java:266)
//             // java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
//             // java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
//             // java.lang.Thread.run(Thread.java:750)
//             //
//             verifyException("org.evosuite.runtime.sandbox.MSecurityManager", e);
//          }
//        } catch(Throwable t) {
//            // Need to catch declared exceptions
//        }
//      }
//    });
//    future.get(4000, TimeUnit.MILLISECONDS);
//  }
//
//  @Test(timeout = 4000)
//  public void test01()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      DRPC dRPC0 = new DRPC(stormMetricsRegistry0, (IAuthorizer) null, 63L);
//      // Undeclared exception!
//      try {
//        dRPC0.returnResult((String) null, "NwT0`In`GBC");
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test02()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      SimpleACLAuthorizer simpleACLAuthorizer0 = new SimpleACLAuthorizer();
//      DRPC dRPC0 = new DRPC(stormMetricsRegistry0, simpleACLAuthorizer0, 1227L);
//      DRPCExecutionException dRPCExecutionException0 = new DRPCExecutionException("A!`*K$u2");
//      // Undeclared exception!
//      try {
//        dRPC0.failRequest((String) null, dRPCExecutionException0);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test03()  throws Throwable  {
//      HashSet<JMXPrincipal> hashSet0 = new HashSet<JMXPrincipal>();
//      Subject subject0 = new Subject(true, hashSet0, hashSet0, hashSet0);
//      ReqContext reqContext0 = new ReqContext(subject0);
//      SimpleACLAuthorizer simpleACLAuthorizer0 = new SimpleACLAuthorizer();
//      // Undeclared exception!
//      try {
//        DRPC.checkAuthorization(reqContext0, simpleACLAuthorizer0, "-1D{54L_", "-1D{54L_");
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.storm.security.auth.authorizer.SimpleACLAuthorizer", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test04()  throws Throwable  {
//      NoopAuthorizer noopAuthorizer0 = new NoopAuthorizer();
//      DRPC dRPC0 = null;
//      try {
//        dRPC0 = new DRPC((StormMetricsRegistry) null, noopAuthorizer0, 0L);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.storm.daemon.drpc.DRPC", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test05()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      DRPCSimpleACLAuthorizer dRPCSimpleACLAuthorizer0 = new DRPCSimpleACLAuthorizer();
//      DRPC dRPC0 = null;
//      try {
//        dRPC0 = new DRPC(stormMetricsRegistry0, dRPCSimpleACLAuthorizer0, 0L);
//        fail("Expecting exception: IllegalArgumentException");
//
//      } catch(IllegalArgumentException e) {
//         //
//         // Non-positive period.
//         //
//         verifyException("java.util.Timer", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test06()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      DRPCSimpleACLAuthorizer dRPCSimpleACLAuthorizer0 = new DRPCSimpleACLAuthorizer();
//      stormMetricsRegistry0.registerHistogram("drpc:num-server-timedout-requests");
//      DRPC dRPC0 = null;
//      try {
//        dRPC0 = new DRPC(stormMetricsRegistry0, dRPCSimpleACLAuthorizer0, 1112L);
//        fail("Expecting exception: IllegalArgumentException");
//
//      } catch(IllegalArgumentException e) {
//         //
//         // drpc:num-server-timedout-requests is already used for a different type of metric
//         //
//         verifyException("com.codahale.metrics.MetricRegistry", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test07()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      DRPC dRPC0 = null;
//      try {
//        dRPC0 = new DRPC(stormMetricsRegistry0, (Map<String, Object>) null);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.storm.daemon.drpc.DRPC", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test08()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
//      stormMetricsRegistry0.registerTimer("drpc:num-result-calls");
//      DRPC dRPC0 = null;
//      try {
//        dRPC0 = new DRPC(stormMetricsRegistry0, hashMap0);
//        fail("Expecting exception: IllegalArgumentException");
//
//      } catch(IllegalArgumentException e) {
//         //
//         // drpc:num-result-calls is already used for a different type of metric
//         //
//         verifyException("com.codahale.metrics.MetricRegistry", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test09()  throws Throwable  {
//    Future<?> future = executor.submit(new Runnable(){
//            @Override public void run() {
//        try {
//          StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//          DRPCSimpleACLAuthorizer dRPCSimpleACLAuthorizer0 = new DRPCSimpleACLAuthorizer();
//          DRPC dRPC0 = new DRPC(stormMetricsRegistry0, dRPCSimpleACLAuthorizer0, 30000L);
//          RequestFactory<BlockingOutstandingRequest> requestFactory0 = BlockingOutstandingRequest.FACTORY;
//          // Undeclared exception!
//          try {
//            dRPC0.execute("fOuO);.!uZ7^ !<:$Y", "fOuO);.!uZ7^ !<:$Y", requestFactory0);
//            fail("Expecting exception: SecurityException");
//
//          } catch(SecurityException e) {
//             //
//             // Security manager blocks (\"javax.security.auth.AuthPermission\" \"getSubject\")
//             // java.lang.Thread.getStackTrace(Thread.java:1564)
//             // org.evosuite.runtime.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:434)
//             // javax.security.auth.Subject.getSubject(Subject.java:287)
//             // org.apache.storm.security.auth.ReqContext.<init>(ReqContext.java:51)
//             // org.apache.storm.security.auth.ReqContext.lambda$static$0(ReqContext.java:42)
//             // java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
//             // java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
//             // java.lang.ThreadLocal.get(ThreadLocal.java:172)
//             // org.apache.storm.security.auth.ReqContext.context(ReqContext.java:78)
//             // org.apache.storm.daemon.drpc.DRPC$AuthorizationSupport.checkCurrent(DRPC.java:187)
//             // org.apache.storm.daemon.drpc.DRPC$AuthorizationSupport.access$800(DRPC.java:164)
//             // org.apache.storm.daemon.drpc.DRPC.execute(DRPC.java:138)
//             // sun.reflect.GeneratedMethodAccessor205.invoke(Unknown Source)
//             // sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
//             // java.lang.reflect.Method.invoke(Method.java:498)
//             // org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:257)
//             // org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169)
//             // org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:220)
//             // org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307)
//             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213)
//             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55)
//             // java.util.concurrent.FutureTask.run(FutureTask.java:266)
//             // java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
//             // java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
//             // java.lang.Thread.run(Thread.java:750)
//             //
//             verifyException("org.evosuite.runtime.sandbox.MSecurityManager", e);
//          }
//        } catch(Throwable t) {
//            // Need to catch declared exceptions
//        }
//      }
//    });
//    future.get(4000, TimeUnit.MILLISECONDS);
//  }
//
//  @Test(timeout = 4000)
//  public void test10()  throws Throwable  {
//      HashSet<JMXPrincipal> hashSet0 = new HashSet<JMXPrincipal>();
//      JMXPrincipal jMXPrincipal0 = new JMXPrincipal("");
//      hashSet0.add(jMXPrincipal0);
//      Subject subject0 = new Subject(true, hashSet0, hashSet0, hashSet0);
//      ReqContext reqContext0 = new ReqContext(subject0);
//      DenyAuthorizer denyAuthorizer0 = new DenyAuthorizer();
//      try {
//        DRPC.checkAuthorization(reqContext0, denyAuthorizer0, "m,P;o0", "execute");
//        fail("Expecting exception: Exception");
//
//      } catch(Exception e) {
//         //
//         // DRPC request 'm,P;o0' for '' user is not authorized
//         //
//         verifyException("org.apache.storm.daemon.drpc.DRPC$AuthorizationSupport", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test11()  throws Throwable  {
//      HashSet<JMXPrincipal> hashSet0 = new HashSet<JMXPrincipal>();
//      Subject subject0 = new Subject(true, hashSet0, hashSet0, hashSet0);
//      ReqContext reqContext0 = new ReqContext(subject0);
//      DenyAuthorizer denyAuthorizer0 = new DenyAuthorizer();
//      try {
//        DRPC.checkAuthorization(reqContext0, denyAuthorizer0, "m,P;o0", "execute");
//        fail("Expecting exception: Exception");
//
//      } catch(Exception e) {
//         //
//         // DRPC request 'm,P;o0' for 'unknown' user is not authorized
//         //
//         verifyException("org.apache.storm.daemon.drpc.DRPC$AuthorizationSupport", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test12()  throws Throwable  {
//      DRPC.checkAuthorization((ReqContext) null, (IAuthorizer) null, "", "");
//  }
//
//  @Test(timeout = 4000)
//  public void test13()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
//      DRPC dRPC0 = new DRPC(stormMetricsRegistry0, hashMap0);
//      DRPCExecutionException dRPCExecutionException0 = new DRPCExecutionException("");
//      dRPC0.failRequest("", dRPCExecutionException0);
//      assertTrue(dRPCExecutionException0.is_set_msg());
//  }
//
//  @Test(timeout = 4000)
//  public void test14()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
//      DRPC dRPC0 = new DRPC(stormMetricsRegistry0, hashMap0);
//      dRPC0.returnResult("", "");
//  }
//
//  @Test(timeout = 4000)
//  public void test15()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
//      DRPC dRPC0 = new DRPC(stormMetricsRegistry0, hashMap0);
//      dRPC0.close();
//  }
//
//  @Test(timeout = 4000)
//  public void test16()  throws Throwable  {
//      Subject subject0 = new Subject();
//      ReqContext reqContext0 = new ReqContext(subject0);
//      ImpersonationAuthorizer impersonationAuthorizer0 = new ImpersonationAuthorizer();
//      DRPC.checkAuthorization(reqContext0, impersonationAuthorizer0, "", "");
//      assertEquals(1, reqContext0.requestID());
//  }
//
//  @Test(timeout = 4000)
//  public void test17()  throws Throwable  {
//    Future<?> future = executor.submit(new Runnable(){
//            @Override public void run() {
//        try {
//          StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//          HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
//          DRPC dRPC0 = new DRPC(stormMetricsRegistry0, hashMap0);
//          // Undeclared exception!
//          try {
//            dRPC0.fetchRequest("");
//            fail("Expecting exception: SecurityException");
//
//          } catch(SecurityException e) {
//             //
//             // Security manager blocks (\"javax.security.auth.AuthPermission\" \"getSubject\")
//             // java.lang.Thread.getStackTrace(Thread.java:1564)
//             // org.evosuite.runtime.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:434)
//             // javax.security.auth.Subject.getSubject(Subject.java:287)
//             // org.apache.storm.security.auth.ReqContext.<init>(ReqContext.java:51)
//             // org.apache.storm.security.auth.ReqContext.lambda$static$0(ReqContext.java:42)
//             // java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
//             // java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
//             // java.lang.ThreadLocal.get(ThreadLocal.java:172)
//             // org.apache.storm.security.auth.ReqContext.context(ReqContext.java:78)
//             // org.apache.storm.daemon.drpc.DRPC$AuthorizationSupport.checkCurrent(DRPC.java:187)
//             // org.apache.storm.daemon.drpc.DRPC$AuthorizationSupport.access$800(DRPC.java:164)
//             // org.apache.storm.daemon.drpc.DRPC.fetchRequest(DRPC.java:111)
//             // sun.reflect.GeneratedMethodAccessor193.invoke(Unknown Source)
//             // sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
//             // java.lang.reflect.Method.invoke(Method.java:498)
//             // org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:257)
//             // org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169)
//             // org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:220)
//             // org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307)
//             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213)
//             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55)
//             // java.util.concurrent.FutureTask.run(FutureTask.java:266)
//             // java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
//             // java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
//             // java.lang.Thread.run(Thread.java:750)
//             //
//             verifyException("org.evosuite.runtime.sandbox.MSecurityManager", e);
//          }
//        } catch(Throwable t) {
//            // Need to catch declared exceptions
//        }
//      }
//    });
//    future.get(4000, TimeUnit.MILLISECONDS);
//  }
//}
