package org.apache.storm.daemon.drpc_4.llm;

import org.apache.storm.Config;
import org.apache.storm.daemon.drpc.refactored.four.DRPC;
import org.apache.storm.daemon.drpc.OutstandingRequest;
import org.apache.storm.daemon.drpc.RequestFactory;
import org.apache.storm.generated.AuthorizationException;
import org.apache.storm.generated.DRPCExecutionException;
import org.apache.storm.generated.DRPCRequest;  // FIXED THIS MANUALLY
import org.apache.storm.security.auth.IAuthorizer;
import org.apache.storm.security.auth.ReqContext;
import org.junit.Before;

import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.Map;
import java.util.concurrent.ArrayBlockingQueue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicReference;

import static org.junit.Assert.*;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.fail;

/**
 * Test suite for DRPC.
 *
 * The tests are intentionally written from the public/protected contract inferred from
 * the supplied requirements only. Mock/stub implementations are used to avoid coupling
 * the test intent to external infrastructure.
 */


/** CLASS FIXED MANUALLY */
public class Zsp4DrpcTest {

    // ### Test START ###

    private static final String FUNCTION = "try";
    private static final String UNKNOWN_FUNCTION = "notExistingFunction";
    private static final String ARGS = "args";
    private static final String RESULT = "done";
    private static final String FAILURE_MESSAGE = "failed";

    private DRPC drpc;

    @Before
    public void setUp() {
        drpc = newTestSubject();
    }

    // TESTS ARE ALL WRONG, THIS CLASS WAS GENERATED BY AN LLM WITHOUT SOURCE CODE !

    // @Test
    public void fetchRequest_whenFunctionNameNull_shouldReturnNullOrThrowAuthorizationExceptionOnly() throws Exception {
        try {
            DRPCRequest request = drpc.fetchRequest(null);
            assertNull("A null function should not resolve to a queued request.", request);
        } catch (AuthorizationException expectedAlsoAcceptable) {
            assertNotNull(expectedAlsoAcceptable);
        }
    }

    // @Test
    public void fetchRequest_whenFunctionNameEmpty_shouldReturnNullOrThrowAuthorizationExceptionOnly() throws Exception {
        try {
            DRPCRequest request = drpc.fetchRequest("");
            assertNull("An empty function should not resolve to a queued request.", request);
        } catch (AuthorizationException expectedAlsoAcceptable) {
            assertNotNull(expectedAlsoAcceptable);
        }
    }

    // @Test
    public void fetchRequest_whenNoRequestExistsForFunction_shouldReturnNull() throws Exception {
        DRPCRequest request = drpc.fetchRequest(UNKNOWN_FUNCTION);
        assertNull("A valid but not-correct function name is not associated with a pending request.", request);
    }

    // @Test
    public void fetchRequest_afterExecute_shouldReturnPreviouslyGeneratedRequest() throws Exception {
        TestOutstandingRequest outstanding = drpc.execute(FUNCTION, ARGS, new ValidRequestFactory());

        DRPCRequest fetched = drpc.fetchRequest(FUNCTION);

        assertNotNull("execute() must create and queue a request retrievable by fetchRequest().", fetched);
        assertNotNull("The request generated by execute() should be exposed to the caller.", outstanding.request);
        assertEquals("fetchRequest() should return the same request id generated by execute().",
                outstanding.request.get_request_id(), fetched.get_request_id());
        assertEquals("fetchRequest() should preserve function arguments.", ARGS, fetched.get_func_args());
    }

    // @Test
    public void execute_whenFunctionNameNullAndFactoryValid_shouldReturnOutstandingOrThrowAuthorizationExceptionOnly() throws Exception {
        try {
            TestOutstandingRequest outstanding = drpc.execute(null, ARGS, new ValidRequestFactory());
            assertNotNull("A valid factory should be used even when function is a boundary/null partition.", outstanding);
        } catch (AuthorizationException expectedAlsoAcceptable) {
            assertNotNull(expectedAlsoAcceptable);
        }
    }

    // @Test
    public void execute_whenFunctionNameEmptyAndFactoryValid_shouldReturnOutstandingOrThrowAuthorizationExceptionOnly() throws Exception {
        try {
            TestOutstandingRequest outstanding = drpc.execute("", ARGS, new ValidRequestFactory());
            assertNotNull("A valid factory should be used for the empty-string boundary partition when permitted.", outstanding);
        } catch (AuthorizationException expectedAlsoAcceptable) {
            assertNotNull(expectedAlsoAcceptable);
        }
    }

    // @Test
    public void execute_whenArgsNullAndFactoryValid_shouldCreateRequestWithNullArgs() throws Exception {
        TestOutstandingRequest outstanding = drpc.execute(FUNCTION, null, new ValidRequestFactory());

        assertNotNull(outstanding);
        assertNotNull(outstanding.request);
        assertNull("Null arguments should be preserved in the generated DRPCRequest.", outstanding.request.get_func_args());
    }

    // @Test
    public void execute_whenArgsEmptyAndFactoryValid_shouldCreateRequestWithEmptyArgs() throws Exception {
        TestOutstandingRequest outstanding = drpc.execute(FUNCTION, "", new ValidRequestFactory());

        assertNotNull(outstanding);
        assertNotNull(outstanding.request);
        assertEquals("The empty-string boundary argument should be preserved.", "", outstanding.request.get_func_args());
    }

    // @Test
    public void execute_whenFactoryNull_shouldThrowNullPointerExceptionOrAuthorizationException() throws Exception {
        try {
            drpc.execute(FUNCTION, ARGS, null);
            fail("A null factory cannot create an outstanding request and should fail fast.");
        } catch (NullPointerException expected) {
            assertNotNull(expected);
        } catch (AuthorizationException expectedAlsoAcceptable) {
            assertNotNull(expectedAlsoAcceptable);
        }
    }

    // @Test
    public void execute_whenFactoryReturnsNull_shouldReturnNullOrThrowNullPointerException() throws Exception {
        try {
            TestOutstandingRequest outstanding = drpc.execute(FUNCTION, ARGS, new NullReturningRequestFactory());
            assertNull("A not-valid factory is defined as one returning null.", outstanding);
        } catch (NullPointerException expectedAlsoAcceptable) {
            assertNotNull(expectedAlsoAcceptable);
        }
    }

    // @Test
    public void returnResult_whenRequestExists_shouldCompleteExecuteBlockingWithResult() throws Exception {
        final AtomicReference<String> blockingResult = new AtomicReference<String>();
        final AtomicReference<Throwable> blockingFailure = new AtomicReference<Throwable>();
        final CountDownLatch requestQueued = new CountDownLatch(1);
        final CountDownLatch completed = new CountDownLatch(1);

        Thread clientThread = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    requestQueued.countDown();
                    blockingResult.set(drpc.executeBlocking(FUNCTION, ARGS));
                } catch (Throwable t) {
                    blockingFailure.set(t);
                } finally {
                    completed.countDown();
                }
            }
        });
        clientThread.start();

        assertTrue("The blocking request should be started.", requestQueued.await(1, TimeUnit.SECONDS));
        DRPCRequest queued = waitForRequest(FUNCTION);
        assertNotNull("executeBlocking() should enqueue a request visible via fetchRequest().", queued);

        drpc.returnResult(queued.get_request_id(), RESULT);

        assertTrue("returnResult() should unblock executeBlocking().", completed.await(3, TimeUnit.SECONDS));
        assertNull("executeBlocking() should not fail when returnResult() is used.", blockingFailure.get());
        assertEquals("executeBlocking() should return the result provided to returnResult().", RESULT, blockingResult.get());
    }

    // @Test
    public void returnResult_whenIdNull_shouldNotCompleteAnyKnownRequestOrShouldThrowAuthorizationException() throws Exception {
        try {
            drpc.returnResult(null, RESULT);
        } catch (AuthorizationException expectedAlsoAcceptable) {
            assertNotNull(expectedAlsoAcceptable);
        } catch (NullPointerException expectedAlsoAcceptable) {
            assertNotNull(expectedAlsoAcceptable);
        }
    }

    // @Test
    public void returnResult_whenIdEmpty_shouldNotCompleteAnyKnownRequestOrShouldThrowAuthorizationException() throws Exception {
        try {
            drpc.returnResult("", RESULT);
        } catch (AuthorizationException expectedAlsoAcceptable) {
            assertNotNull(expectedAlsoAcceptable);
        }
    }

    // @Test
    public void returnResult_whenIdDoesNotExist_shouldNotThrowUnexpectedException() throws Exception {
        drpc.returnResult("1", RESULT);
    }

    // @Test
    public void returnResult_whenResultNull_shouldCompleteBlockingRequestWithNull() throws Exception {
        final AtomicReference<String> blockingResult = new AtomicReference<String>("initial");
        final AtomicReference<Throwable> blockingFailure = new AtomicReference<Throwable>();
        final CountDownLatch completed = new CountDownLatch(1);

        Thread clientThread = startExecuteBlockingThread(blockingResult, blockingFailure, completed);
        DRPCRequest queued = waitForRequest(FUNCTION);
        assertNotNull(queued);

        drpc.returnResult(queued.get_request_id(), null);

        assertTrue(completed.await(3, TimeUnit.SECONDS));
        assertNull(blockingFailure.get());
        assertNull("Null result is a distinct equivalence class and should be propagated.", blockingResult.get());
        clientThread.join(1000);
    }

    // @Test
    public void returnResult_whenResultEmpty_shouldCompleteBlockingRequestWithEmptyString() throws Exception {
        final AtomicReference<String> blockingResult = new AtomicReference<String>();
        final AtomicReference<Throwable> blockingFailure = new AtomicReference<Throwable>();
        final CountDownLatch completed = new CountDownLatch(1);

        Thread clientThread = startExecuteBlockingThread(blockingResult, blockingFailure, completed);
        DRPCRequest queued = waitForRequest(FUNCTION);
        assertNotNull(queued);

        drpc.returnResult(queued.get_request_id(), "");

        assertTrue(completed.await(3, TimeUnit.SECONDS));
        assertNull(blockingFailure.get());
        assertEquals("", blockingResult.get());
        clientThread.join(1000);
    }

    // @Test
    public void failRequest_whenRequestExistsAndExceptionHasMessage_shouldCompleteExecuteBlockingWithExecutionException() throws Exception {
        final AtomicReference<String> blockingResult = new AtomicReference<String>();
        final AtomicReference<Throwable> blockingFailure = new AtomicReference<Throwable>();
        final CountDownLatch completed = new CountDownLatch(1);

        Thread clientThread = startExecuteBlockingThread(blockingResult, blockingFailure, completed);
        DRPCRequest queued = waitForRequest(FUNCTION);
        assertNotNull(queued);

        drpc.failRequest(queued.get_request_id(), executionException(FAILURE_MESSAGE));

        assertTrue("failRequest() should unblock executeBlocking().", completed.await(3, TimeUnit.SECONDS));
        assertNull("No successful result is expected after failRequest().", blockingResult.get());
        assertTrue("executeBlocking() should fail with DRPCExecutionException.",
                blockingFailure.get() instanceof DRPCExecutionException);
        assertEquals("The exception message should be propagated from failRequest().",
                FAILURE_MESSAGE, ((DRPCExecutionException) blockingFailure.get()).get_msg());
        clientThread.join(1000);
    }

    // @Test
    public void failRequest_whenExceptionHasNoMessage_shouldCompleteWithExecutionExceptionHavingNullMessage() throws Exception {
        final AtomicReference<Throwable> blockingFailure = new AtomicReference<Throwable>();
        final CountDownLatch completed = new CountDownLatch(1);
        final AtomicReference<String> blockingResult = new AtomicReference<String>();

        Thread clientThread = startExecuteBlockingThread(blockingResult, blockingFailure, completed);
        DRPCRequest queued = waitForRequest(FUNCTION);
        assertNotNull(queued);

        drpc.failRequest(queued.get_request_id(), executionException(null));

        assertTrue(completed.await(3, TimeUnit.SECONDS));
        assertTrue(blockingFailure.get() instanceof DRPCExecutionException);
        assertNull("A not-valid exception instance has no message and should propagate null.",
                ((DRPCExecutionException) blockingFailure.get()).get_msg());
        clientThread.join(1000);
    }

    // @Test
    public void failRequest_whenExceptionNull_shouldThrowNullPointerExceptionOrAuthorizationException() throws Exception {
        try {
            drpc.failRequest("1", null);
            fail("A null failure exception cannot provide the failure payload.");
        } catch (NullPointerException expected) {
            assertNotNull(expected);
        } catch (AuthorizationException expectedAlsoAcceptable) {
            assertNotNull(expectedAlsoAcceptable);
        }
    }

    // @Test
    public void failRequest_whenIdDoesNotExist_shouldNotThrowUnexpectedException() throws Exception {
        drpc.failRequest("1", executionException(FAILURE_MESSAGE));
    }

    // @Test
    public void executeBlocking_whenRequestIsReturned_shouldReturnProvidedResult() throws Exception {
        final AtomicReference<String> blockingResult = new AtomicReference<String>();
        final AtomicReference<Throwable> blockingFailure = new AtomicReference<Throwable>();
        final CountDownLatch completed = new CountDownLatch(1);

        Thread clientThread = startExecuteBlockingThread(blockingResult, blockingFailure, completed);
        DRPCRequest queued = waitForRequest(FUNCTION);
        assertNotNull(queued);

        drpc.returnResult(queued.get_request_id(), RESULT);

        assertTrue(completed.await(3, TimeUnit.SECONDS));
        assertNull(blockingFailure.get());
        assertEquals(RESULT, blockingResult.get());
        clientThread.join(1000);
    }

    // @Test
    public void executeBlocking_whenRequestFails_shouldThrowExecutionExceptionWithProvidedFailureMessage() throws Exception {
        final AtomicReference<String> blockingResult = new AtomicReference<String>();
        final AtomicReference<Throwable> blockingFailure = new AtomicReference<Throwable>();
        final CountDownLatch completed = new CountDownLatch(1);

        Thread clientThread = startExecuteBlockingThread(blockingResult, blockingFailure, completed);
        DRPCRequest queued = waitForRequest(FUNCTION);
        assertNotNull(queued);

        drpc.failRequest(queued.get_request_id(), executionException(FAILURE_MESSAGE));

        assertTrue(completed.await(3, TimeUnit.SECONDS));
        assertNull(blockingResult.get());
        assertTrue(blockingFailure.get() instanceof DRPCExecutionException);
        assertEquals(FAILURE_MESSAGE, ((DRPCExecutionException) blockingFailure.get()).get_msg());
        clientThread.join(1000);
    }

    // @Test
    public void executeBlocking_whenFunctionNull_shouldQueueRequestOrThrowAuthorizationException() throws Exception {
        try {
            final AtomicReference<String> blockingResult = new AtomicReference<String>();
            final AtomicReference<Throwable> blockingFailure = new AtomicReference<Throwable>();
            final CountDownLatch completed = new CountDownLatch(1);

            Thread clientThread = startExecuteBlockingThread(null, ARGS, blockingResult, blockingFailure, completed);
            DRPCRequest queued = waitForRequest(null);
            if (queued != null) {
                drpc.returnResult(queued.get_request_id(), RESULT);
                assertTrue(completed.await(3, TimeUnit.SECONDS));
                assertEquals(RESULT, blockingResult.get());
            }
            clientThread.join(1000);
        } catch (AuthorizationException expectedAlsoAcceptable) {
            assertNotNull(expectedAlsoAcceptable);
        }
    }

    // @Test
    public void executeBlocking_whenFunctionEmptyAndArgsEmpty_shouldHandleBoundaryStrings() throws Exception {
        final AtomicReference<String> blockingResult = new AtomicReference<String>();
        final AtomicReference<Throwable> blockingFailure = new AtomicReference<Throwable>();
        final CountDownLatch completed = new CountDownLatch(1);

        Thread clientThread = startExecuteBlockingThread("", "", blockingResult, blockingFailure, completed);
        DRPCRequest queued = waitForRequest("");
        assertNotNull(queued);

        drpc.returnResult(queued.get_request_id(), RESULT);

        assertTrue(completed.await(3, TimeUnit.SECONDS));
        assertNull(blockingFailure.get());
        assertEquals(RESULT, blockingResult.get());
        clientThread.join(1000);
    }

    // @Test
    public void checkAuthorization_whenAlwaysAuthorized_shouldNotThrow() throws Exception {
        drpc.checkAuthorization(ReqContext.context(), new AlwaysAuthorized(), "execute", FUNCTION);
    }

    // @Test(expected = AuthorizationException.class)
    public void checkAuthorization_whenNeverAuthorized_shouldThrowAuthorizationException() throws Exception {
        drpc.checkAuthorization(ReqContext.context(), new NeverAuthorized(), "execute", FUNCTION);
    }

    // @Test
    public void checkAuthorization_whenAuthorizerNull_shouldNotThrow() throws Exception {
        drpc.checkAuthorization(ReqContext.context(), null, "execute", FUNCTION);
    }

    // @Test(expected = RuntimeException.class)
    public void checkAuthorization_whenAuthorizerInvalidThrowsRuntimeException_shouldPropagateRuntimeException() throws Exception {
        drpc.checkAuthorization(ReqContext.context(), new ThrowingAuthorizer(), "execute", FUNCTION);
    }

    // @Test
    public void checkAuthorization_whenReqContextNullAndAlwaysAuthorized_shouldNotThrow() throws Exception {
        drpc.checkAuthorization(null, new AlwaysAuthorized(), "execute", FUNCTION);
    }

    // @Test
    public void checkAuthorization_whenOperationNullAndAlwaysAuthorized_shouldNotThrow() throws Exception {
        drpc.checkAuthorization(ReqContext.context(), new AlwaysAuthorized(), null, FUNCTION);
    }

    // @Test
    public void checkAuthorization_whenOperationEmptyAndAlwaysAuthorized_shouldNotThrow() throws Exception {
        drpc.checkAuthorization(ReqContext.context(), new AlwaysAuthorized(), "", FUNCTION);
    }

    // @Test
    public void checkAuthorization_whenFunctionNullAndAlwaysAuthorized_shouldNotThrow() throws Exception {
        drpc.checkAuthorization(ReqContext.context(), new AlwaysAuthorized(), "execute", null);
    }

    // @Test
    public void checkAuthorization_whenFunctionEmptyAndAlwaysAuthorized_shouldNotThrow() throws Exception {
        drpc.checkAuthorization(ReqContext.context(), new AlwaysAuthorized(), "execute", "");
    }

    // @Test(expected = AuthorizationException.class)
    public void checkAuthorization_whenFunctionNotCorrectAndNeverAuthorized_shouldThrowAuthorizationException() throws Exception {
        drpc.checkAuthorization(ReqContext.context(), new NeverAuthorized(), "execute", UNKNOWN_FUNCTION);
    }

    /**
     * Creates the DRPC test subject while tolerating constructor differences across versions.
     * The preferred constructor is the no-arg constructor; if unavailable, a Map-based
     * configuration constructor is attempted.
     */
    private DRPC newTestSubject() {
        try {
            return DRPC.class.getConstructor().newInstance();
        } catch (Exception noNoArgConstructor) {
            try {
                return DRPC.class.getConstructor(Map.class).newInstance(new Config());
            } catch (Exception noMapConstructor) {
                throw new AssertionError("Unable to instantiate DRPC using known constructors.", noMapConstructor);
            }
        }
    }

    private Thread startExecuteBlockingThread(final AtomicReference<String> blockingResult,
                                              final AtomicReference<Throwable> blockingFailure,
                                              final CountDownLatch completed) {
        return startExecuteBlockingThread(FUNCTION, ARGS, blockingResult, blockingFailure, completed);
    }

    private Thread startExecuteBlockingThread(final String function,
                                              final String args,
                                              final AtomicReference<String> blockingResult,
                                              final AtomicReference<Throwable> blockingFailure,
                                              final CountDownLatch completed) {
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    blockingResult.set(drpc.executeBlocking(function, args));
                } catch (Throwable t) {
                    blockingFailure.set(t);
                } finally {
                    completed.countDown();
                }
            }
        });
        t.start();
        return t;
    }

    private DRPCRequest waitForRequest(String functionName) throws Exception {
        long deadline = System.currentTimeMillis() + 3000L;
        DRPCRequest request = null;
        while (System.currentTimeMillis() < deadline) {
            request = drpc.fetchRequest(functionName);
            if (request != null) {
                return request;
            }
            Thread.sleep(25L);
        }
        return request;
    }

    private DRPCExecutionException executionException(String message) throws Exception {
        DRPCExecutionException e = new DRPCExecutionException();
        e.set_msg(message);
        return e;
    }

    /**
     * Minimal valid OutstandingRequest implementation.
     * Reflection is used so the test remains useful even if the implementation stores
     * request/result/error in superclass fields with version-specific names.
     */
    public static class TestOutstandingRequest extends OutstandingRequest {
        final DRPCRequest request;
        final BlockingQueue<Object> completionQueue = new ArrayBlockingQueue<Object>(1);

        TestOutstandingRequest(String function, DRPCRequest request) {  // ADDED FUNCTION E SUPER MANUALLY
            super(function,request);
            this.request = request;
            injectKnownField("req", request);
            injectKnownField("request", request);
            injectKnownField("_req", request);
        }

        public void returnResult(String result) {
            completionQueue.offer(result);
            injectKnownField("result", result);
            invokeIfPresent("returnResult", new Class<?>[] { String.class }, new Object[] { result });
        }

        public void fail(DRPCExecutionException e) {
            completionQueue.offer(e);
            injectKnownField("e", e);
            injectKnownField("error", e);
            invokeIfPresent("fail", new Class<?>[] { DRPCExecutionException.class }, new Object[] { e });
        }

        private void injectKnownField(String fieldName, Object value) {
            Class<?> c = getClass();
            while (c != null) {
                try {
                    Field f = c.getDeclaredField(fieldName);
                    f.setAccessible(true);
                    f.set(this, value);
                    return;
                } catch (Exception ignored) {
                    c = c.getSuperclass();
                }
            }
        }

        private void invokeIfPresent(String methodName, Class<?>[] parameterTypes, Object[] args) {
            Class<?> c = getClass().getSuperclass();
            while (c != null) {
                try {
                    Method m = c.getDeclaredMethod(methodName, parameterTypes);
                    m.setAccessible(true);
                    m.invoke(this, args);
                    return;
                } catch (NoSuchMethodException ignored) {
                    c = c.getSuperclass();
                } catch (Exception ignored) {
                    return;
                }
            }
        }
    }

    private static class ValidRequestFactory implements RequestFactory<TestOutstandingRequest> {
        @Override
        public TestOutstandingRequest mkRequest(String function, DRPCRequest req) {
            assertNotNull("DRPC should pass a generated request to a valid factory.", req);
            return new TestOutstandingRequest(function, req); // ADDED FUNCTION
        }
    }

    private static class NullReturningRequestFactory implements RequestFactory<TestOutstandingRequest> {
        @Override
        public TestOutstandingRequest mkRequest(String function, DRPCRequest req) {
            return null;
        }
    }

    private static class AlwaysAuthorized implements IAuthorizer {   // IMPLEMENTED METHODS MANUALLY
        @Override
        public void prepare(Map<String, Object> conf) {

        }

        @Override
        public boolean permit(ReqContext context, String operation, Map<String, Object> topoConf) {
            return true;
        }
    }

    private static class NeverAuthorized implements IAuthorizer { // IMPLEMENTED METHODS MANUALLY
        @Override
        public void prepare(Map<String, Object> conf) {

        }

        @Override
        public boolean permit(ReqContext context, String operation, Map<String, Object> topoConf) {
            return false;
        }
    }

    private static class ThrowingAuthorizer implements IAuthorizer { // IMPLEMENTED METHODS MANUALLY
        @Override
        public void prepare(Map<String, Object> conf) {

        }

        @Override
        public boolean permit(ReqContext context, String operation, Map<String, Object> topoConf) { // IMPLEMENTED METHODS MANUALLY
            throw new RuntimeException("invalid authorizer");
        }
    }

    // ### Test END ###
}
