///*
// * This file was automatically generated by EvoSuite
// * Mon Jul 13 16:06:55 GMT 2026
// */
//
//package org.apache.storm.daemon.drpc_2.another.evosuite;
//
//import com.codahale.metrics.MetricRegistry;
//import org.apache.storm.daemon.drpc.BlockingOutstandingRequest;
//import org.apache.storm.daemon.drpc.DRPC;
//import org.apache.storm.daemon.drpc.RequestFactory;
//import org.apache.storm.generated.DRPCExecutionException;
//import org.apache.storm.metric.StormMetricsRegistry;
//import org.apache.storm.metrics2.StormMetricRegistry;
//import org.apache.storm.security.auth.IAuthorizer;
//import org.apache.storm.security.auth.ReqContext;
//import org.apache.storm.security.auth.authorizer.*;
//import org.evosuite.runtime.EvoRunner;
//import org.evosuite.runtime.EvoRunnerParameters;
//import org.junit.Test;
//import org.junit.runner.RunWith;
//
//import javax.security.auth.Subject;
//import java.security.Principal;
//import java.util.HashMap;
//import java.util.Hashtable;
//import java.util.LinkedHashSet;
//import java.util.Map;
//import java.util.concurrent.Future;
//import java.util.concurrent.TimeUnit;
//
//import static org.evosuite.runtime.EvoAssertions.*;
//import static org.junit.Assert.*;
//
//@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true)
//public class DRPC_ESTest extends DRPC_ESTest_scaffolding {
//
//  @Test(timeout = 4000)
//  public void test00()  throws Throwable  {
//      Subject subject0 = new Subject();
//      ReqContext reqContext0 = new ReqContext(subject0);
//      SimpleWhitelistAuthorizer simpleWhitelistAuthorizer0 = new SimpleWhitelistAuthorizer();
//      try {
//        DRPC.checkAuthorization(reqContext0, simpleWhitelistAuthorizer0, "\";T\" d@[KeAl9SQo/", "storm.auth.simple-white-list.users");
//        fail("Expecting exception: Exception");
//
//      } catch(Exception e) {
//         //
//         // DRPC request '\";T\" d@[KeAl9SQo/' for 'unknown' user is not authorized
//         //
//         verifyException("org.apache.storm.daemon.drpc.DRPC$AuthorizationSupport", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test01()  throws Throwable  {
//      LinkedHashSet<Principal> linkedHashSet0 = new LinkedHashSet<Principal>();
//      Subject subject0 = new Subject(true, linkedHashSet0, linkedHashSet0, linkedHashSet0);
//      ReqContext reqContext0 = new ReqContext(subject0);
//      SupervisorSimpleACLAuthorizer supervisorSimpleACLAuthorizer0 = new SupervisorSimpleACLAuthorizer();
//      // Undeclared exception!
//      try {
//        DRPC.checkAuthorization(reqContext0, supervisorSimpleACLAuthorizer0, "Timed Out", "org.apache.storm.daemon.drpc.DRPC$RequestSupport");
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.storm.security.auth.authorizer.SupervisorSimpleACLAuthorizer", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test02()  throws Throwable  {
//    Future<?> future = executor.submit(new Runnable(){
//            @Override public void run() {
//        try {
//          StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//          HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
//          DRPC dRPC0 = new DRPC(stormMetricsRegistry0, hashMap0);
//          // Undeclared exception!
//          try {
//            dRPC0.fetchRequest("Server Shutting Down");
//            fail("Expecting exception: SecurityException");
//
//          } catch(SecurityException e) {
//             //
//             // Security manager blocks (\"javax.security.auth.AuthPermission\" \"getSubject\")
//             // java.lang.Thread.getStackTrace(Thread.java:1564)
//             // org.evosuite.runtime.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:434)
//             // javax.security.auth.Subject.getSubject(Subject.java:287)
//             // org.apache.storm.security.auth.ReqContext.<init>(ReqContext.java:51)
//             // org.apache.storm.security.auth.ReqContext.lambda$static$0(ReqContext.java:42)
//             // java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
//             // java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
//             // java.lang.ThreadLocal.get(ThreadLocal.java:172)
//             // org.apache.storm.security.auth.ReqContext.context(ReqContext.java:78)
//             // org.apache.storm.daemon.drpc.DRPC.fetchRequest(DRPC.java:107)
//             // sun.reflect.GeneratedMethodAccessor251.invoke(Unknown Source)
//             // sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
//             // java.lang.reflect.Method.invoke(Method.java:498)
//             // org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:257)
//             // org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169)
//             // org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:220)
//             // org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307)
//             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213)
//             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55)
//             // java.util.concurrent.FutureTask.run(FutureTask.java:266)
//             // java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
//             // java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
//             // java.lang.Thread.run(Thread.java:750)
//             //
//             verifyException("org.evosuite.runtime.sandbox.MSecurityManager", e);
//          }
//        } catch(Throwable t) {
//            // Need to catch declared exceptions
//        }
//      }
//    });
//    future.get(4000, TimeUnit.MILLISECONDS);
//  }
//
//  @Test(timeout = 4000)
//  public void test03()  throws Throwable  {
//      NoopAuthorizer noopAuthorizer0 = new NoopAuthorizer();
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      DRPC dRPC0 = new DRPC(stormMetricsRegistry0, noopAuthorizer0, 4293L);
//      // Undeclared exception!
//      try {
//        dRPC0.returnResult((String) null, "/-18NIkWR[z$QBn^");
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test04()  throws Throwable  {
//      ImpersonationAuthorizer impersonationAuthorizer0 = new ImpersonationAuthorizer();
//      DRPC dRPC0 = null;
//      try {
//        dRPC0 = new DRPC((StormMetricsRegistry) null, impersonationAuthorizer0, 127L);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.storm.daemon.drpc.DRPC", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test05()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      SimpleWhitelistAuthorizer simpleWhitelistAuthorizer0 = new SimpleWhitelistAuthorizer();
//      stormMetricsRegistry0.registerHistogram("drpc:num-execute-calls");
//      DRPC dRPC0 = null;
//      try {
//        dRPC0 = new DRPC(stormMetricsRegistry0, simpleWhitelistAuthorizer0, 2034L);
//        fail("Expecting exception: IllegalArgumentException");
//
//      } catch(IllegalArgumentException e) {
//         //
//         // drpc:num-execute-calls is already used for a different type of metric
//         //
//         verifyException("com.codahale.metrics.MetricRegistry", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test06()  throws Throwable  {
//      DRPC dRPC0 = null;
//      try {
//        dRPC0 = new DRPC((StormMetricsRegistry) null, (Map<String, Object>) null);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.storm.daemon.drpc.DRPC", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test07()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
//      hashMap0.put("drpc.authorizer", "drpc.authorizer");
//      DRPC dRPC0 = null;
//      try {
//        dRPC0 = new DRPC(stormMetricsRegistry0, hashMap0);
//        fail("Expecting exception: IllegalStateException");
//
//      } catch(IllegalStateException e) {
//         //
//         // java.lang.ClassNotFoundException: Class 'drpc/authorizer.class' should be in target project, but could not be found!
//         //
//         verifyException("org.apache.storm.daemon.drpc.DRPC$AuthorizationSupport", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test08()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      stormMetricsRegistry0.registerTimer("drpc:num-fetchRequest-calls");
//      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
//      DRPC dRPC0 = null;
//      try {
//        dRPC0 = new DRPC(stormMetricsRegistry0, hashMap0);
//        fail("Expecting exception: IllegalArgumentException");
//
//      } catch(IllegalArgumentException e) {
//         //
//         // drpc:num-fetchRequest-calls is already used for a different type of metric
//         //
//         verifyException("com.codahale.metrics.MetricRegistry", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test09()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      Hashtable<String, DRPC> hashtable0 = new Hashtable<String, DRPC>();
//      Hashtable<String, Object> hashtable1 = new Hashtable<String, Object>(hashtable0);
//      StormMetricRegistry stormMetricRegistry0 = new StormMetricRegistry();
//      MetricRegistry metricRegistry0 = stormMetricRegistry0.getRegistry();
//      hashtable1.put("drpc.authorizer", metricRegistry0);
//      DRPC dRPC0 = null;
//      try {
//        dRPC0 = new DRPC(stormMetricsRegistry0, hashtable1);
//        fail("Expecting exception: ClassCastException");
//
//      } catch(ClassCastException e) {
//         //
//         // com.codahale.metrics.MetricRegistry cannot be cast to java.lang.String
//         //
//         verifyException("org.apache.storm.daemon.drpc.DRPC", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test10()  throws Throwable  {
//    Future<?> future = executor.submit(new Runnable(){
//            @Override public void run() {
//        try {
//          StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//          SimpleWhitelistAuthorizer simpleWhitelistAuthorizer0 = new SimpleWhitelistAuthorizer();
//          DRPC dRPC0 = new DRPC(stormMetricsRegistry0, simpleWhitelistAuthorizer0, 986L);
//          RequestFactory<BlockingOutstandingRequest> requestFactory0 = BlockingOutstandingRequest.FACTORY;
//          // Undeclared exception!
//          try {
//            dRPC0.execute("storm.auth.simple-white-list.users", "storm.auth.simple-white-list.users", requestFactory0);
//            fail("Expecting exception: SecurityException");
//
//          } catch(SecurityException e) {
//             //
//             // Security manager blocks (\"javax.security.auth.AuthPermission\" \"getSubject\")
//             // java.lang.Thread.getStackTrace(Thread.java:1564)
//             // org.evosuite.runtime.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:434)
//             // javax.security.auth.Subject.getSubject(Subject.java:287)
//             // org.apache.storm.security.auth.ReqContext.<init>(ReqContext.java:51)
//             // org.apache.storm.security.auth.ReqContext.lambda$static$0(ReqContext.java:42)
//             // java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
//             // java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
//             // java.lang.ThreadLocal.get(ThreadLocal.java:172)
//             // org.apache.storm.security.auth.ReqContext.context(ReqContext.java:78)
//             // org.apache.storm.daemon.drpc.DRPC.execute(DRPC.java:135)
//             // sun.reflect.GeneratedMethodAccessor250.invoke(Unknown Source)
//             // sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
//             // java.lang.reflect.Method.invoke(Method.java:498)
//             // org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:257)
//             // org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169)
//             // org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:220)
//             // org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307)
//             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213)
//             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55)
//             // java.util.concurrent.FutureTask.run(FutureTask.java:266)
//             // java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
//             // java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
//             // java.lang.Thread.run(Thread.java:750)
//             //
//             verifyException("org.evosuite.runtime.sandbox.MSecurityManager", e);
//          }
//        } catch(Throwable t) {
//            // Need to catch declared exceptions
//        }
//      }
//    });
//    future.get(4000, TimeUnit.MILLISECONDS);
//  }
//
//  @Test(timeout = 4000)
//  public void test11()  throws Throwable  {
//      DenyAuthorizer denyAuthorizer0 = new DenyAuthorizer();
//      // Undeclared exception!
//      try {
//        DRPC.checkAuthorization((ReqContext) null, denyAuthorizer0, (String) null, (String) null);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.storm.daemon.drpc.DRPC$AuthorizationSupport", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test12()  throws Throwable  {
//      Subject subject0 = new Subject();
//      ReqContext reqContext0 = new ReqContext(subject0);
//      DRPC.checkAuthorization(reqContext0, (IAuthorizer) null, (String) null, (String) null);
//      assertEquals(1, reqContext0.requestID());
//  }
//
//  @Test(timeout = 4000)
//  public void test13()  throws Throwable  {
//      NoopAuthorizer noopAuthorizer0 = new NoopAuthorizer();
//      DRPC.checkAuthorization((ReqContext) null, noopAuthorizer0, "&e/a7:", "&e/a7:");
//  }
//
//  @Test(timeout = 4000)
//  public void test14()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      SimpleWhitelistAuthorizer simpleWhitelistAuthorizer0 = new SimpleWhitelistAuthorizer();
//      DRPC dRPC0 = new DRPC(stormMetricsRegistry0, simpleWhitelistAuthorizer0, 2026L);
//      DRPCExecutionException dRPCExecutionException0 = new DRPCExecutionException();
//      dRPC0.failRequest("storm.auth.simple-white-list.users", dRPCExecutionException0);
//      assertNull(dRPCExecutionException0.get_type());
//  }
//
//  @Test(timeout = 4000)
//  public void test15()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      DRPCSimpleACLAuthorizer dRPCSimpleACLAuthorizer0 = new DRPCSimpleACLAuthorizer();
//      DRPC dRPC0 = new DRPC(stormMetricsRegistry0, dRPCSimpleACLAuthorizer0, 2L);
//      dRPC0.returnResult("function.name", "invocation.user");
//  }
//
//  @Test(timeout = 4000)
//  public void test16()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      DRPCSimpleACLAuthorizer dRPCSimpleACLAuthorizer0 = new DRPCSimpleACLAuthorizer();
//      DRPC dRPC0 = new DRPC(stormMetricsRegistry0, dRPCSimpleACLAuthorizer0, 2L);
//      dRPC0.close();
//  }
//
//  @Test(timeout = 4000)
//  public void test17()  throws Throwable  {
//    Future<?> future = executor.submit(new Runnable(){
//            @Override public void run() {
//        try {
//          StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//          DRPCSimpleACLAuthorizer dRPCSimpleACLAuthorizer0 = new DRPCSimpleACLAuthorizer();
//          DRPC dRPC0 = new DRPC(stormMetricsRegistry0, dRPCSimpleACLAuthorizer0, 2L);
//          // Undeclared exception!
//          try {
//            dRPC0.executeBlocking("client.users", "function.name");
//            fail("Expecting exception: SecurityException");
//
//          } catch(SecurityException e) {
//             //
//             // Security manager blocks (\"javax.security.auth.AuthPermission\" \"getSubject\")
//             // java.lang.Thread.getStackTrace(Thread.java:1564)
//             // org.evosuite.runtime.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:434)
//             // javax.security.auth.Subject.getSubject(Subject.java:287)
//             // org.apache.storm.security.auth.ReqContext.<init>(ReqContext.java:51)
//             // org.apache.storm.security.auth.ReqContext.lambda$static$0(ReqContext.java:42)
//             // java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
//             // java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
//             // java.lang.ThreadLocal.get(ThreadLocal.java:172)
//             // org.apache.storm.security.auth.ReqContext.context(ReqContext.java:78)
//             // org.apache.storm.daemon.drpc.DRPC.execute(DRPC.java:135)
//             // org.apache.storm.daemon.drpc.DRPC.executeBlocking(DRPC.java:147)
//             // sun.reflect.GeneratedMethodAccessor243.invoke(Unknown Source)
//             // sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
//             // java.lang.reflect.Method.invoke(Method.java:498)
//             // org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:257)
//             // org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169)
//             // org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:220)
//             // org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307)
//             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213)
//             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55)
//             // java.util.concurrent.FutureTask.run(FutureTask.java:266)
//             // java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
//             // java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
//             // java.lang.Thread.run(Thread.java:750)
//             //
//             verifyException("org.evosuite.runtime.sandbox.MSecurityManager", e);
//          }
//        } catch(Throwable t) {
//            // Need to catch declared exceptions
//        }
//      }
//    });
//    future.get(4000, TimeUnit.MILLISECONDS);
//  }
//
//  @Test(timeout = 4000)
//  public void test18()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
//      DRPC dRPC0 = new DRPC(stormMetricsRegistry0, hashMap0);
//      DRPCExecutionException dRPCExecutionException0 = new DRPCExecutionException((String) null);
//      // Undeclared exception!
//      try {
//        dRPC0.failRequest((String) null, dRPCExecutionException0);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test19()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      DRPCSimpleACLAuthorizer dRPCSimpleACLAuthorizer0 = new DRPCSimpleACLAuthorizer();
//      DRPC dRPC0 = null;
//      try {
//        dRPC0 = new DRPC(stormMetricsRegistry0, dRPCSimpleACLAuthorizer0, 1L);
//        fail("Expecting exception: IllegalArgumentException");
//
//      } catch(IllegalArgumentException e) {
//         //
//         // Non-positive period.
//         //
//         verifyException("java.util.Timer", e);
//      }
//  }
//}
