///*
// * This file was automatically generated by EvoSuite
// * Tue Jun 30 15:51:06 GMT 2026
// */
//
//package org.apache.storm.daemon.drpc.evosuite;
//
//import org.apache.storm.daemon.drpc.BlockingOutstandingRequest;
//import org.apache.storm.daemon.drpc.DRPC;
//import org.apache.storm.daemon.drpc.RequestFactory;
//import org.apache.storm.generated.DRPCExecutionException;
//import org.apache.storm.metric.StormMetricsRegistry;
//import org.apache.storm.security.auth.IAuthorizer;
//import org.apache.storm.security.auth.ReqContext;
//import org.apache.storm.security.auth.authorizer.*;
//import org.evosuite.runtime.EvoRunner;
//import org.evosuite.runtime.EvoRunnerParameters;
//import org.junit.Test;
//import org.junit.runner.RunWith;
//
//import javax.management.remote.JMXPrincipal;
//import javax.security.auth.Subject;
//import java.util.HashMap;
//import java.util.LinkedHashSet;
//import java.util.Map;
//import java.util.concurrent.Future;
//import java.util.concurrent.TimeUnit;
//
//import static org.evosuite.runtime.EvoAssertions.verifyException;
//import static org.junit.Assert.assertEquals;
//import static org.junit.Assert.fail;
//
//@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true)
//public class DRPC_ESTest extends DRPC_ESTest_scaffolding {
//
//  @Test(timeout = 4000)
//  public void test00()  throws Throwable  {
//    Future<?> future = executor.submit(new Runnable(){
//            @Override public void run() {
//        try {
//          StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//          DRPCSimpleACLAuthorizer dRPCSimpleACLAuthorizer0 = new DRPCSimpleACLAuthorizer();
//          DRPC dRPC0 = new DRPC(stormMetricsRegistry0, dRPCSimpleACLAuthorizer0, 9223372036854775807L);
//          // Undeclared exception!
//          try {
//            dRPC0.executeBlocking("]k{7q' +KhAw", "function.name");
//            fail("Expecting exception: SecurityException");
//
//          } catch(SecurityException e) {
//             //
//             // Security manager blocks (\"javax.security.auth.AuthPermission\" \"getSubject\")
//             // java.lang.Thread.getStackTrace(Thread.java:1564)
//             // org.evosuite.runtime.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:434)
//             // javax.security.auth.Subject.getSubject(Subject.java:287)
//             // org.apache.storm.security.auth.ReqContext.<init>(ReqContext.java:51)
//             // org.apache.storm.security.auth.ReqContext.lambda$static$0(ReqContext.java:42)
//             // java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
//             // java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
//             // java.lang.ThreadLocal.get(ThreadLocal.java:172)
//             // org.apache.storm.security.auth.ReqContext.context(ReqContext.java:78)
//             // org.apache.storm.daemon.drpc.DRPC.checkAuthorization(DRPC.java:139)
//             // org.apache.storm.daemon.drpc.DRPC.execute(DRPC.java:221)
//             // org.apache.storm.daemon.drpc.DRPC.executeBlocking(DRPC.java:232)
//             // sun.reflect.GeneratedMethodAccessor149.invoke(Unknown Source)
//             // sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
//             // java.lang.reflect.Method.invoke(Method.java:498)
//             // org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:257)
//             // org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169)
//             // org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:220)
//             // org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307)
//             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213)
//             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55)
//             // java.util.concurrent.FutureTask.run(FutureTask.java:266)
//             // java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
//             // java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
//             // java.lang.Thread.run(Thread.java:750)
//             //
//             verifyException("org.evosuite.runtime.sandbox.MSecurityManager", e);
//          }
//        } catch(Throwable t) {
//            // Need to catch declared exceptions
//        }
//      }
//    });
//    future.get(4000, TimeUnit.MILLISECONDS);
//  }
//
//  @Test(timeout = 4000)
//  public void test01()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
//      DRPC dRPC0 = new DRPC(stormMetricsRegistry0, hashMap0);
//      dRPC0.returnResult("05#", "");
//  }
//
//  @Test(timeout = 4000)
//  public void test02()  throws Throwable  {
//      DenyAuthorizer denyAuthorizer0 = new DenyAuthorizer();
//      LinkedHashSet<JMXPrincipal> linkedHashSet0 = new LinkedHashSet<JMXPrincipal>();
//      Subject subject0 = new Subject(true, linkedHashSet0, linkedHashSet0, linkedHashSet0);
//      ReqContext reqContext0 = new ReqContext(subject0);
//      try {
//        DRPC.checkAuthorization(reqContext0, denyAuthorizer0, (String) null, "wbGU4Z=");
//        fail("Expecting exception: Exception");
//
//      } catch(Exception e) {
//         //
//         // DRPC request 'null' for 'unknown' user is not authorized
//         //
//         verifyException("org.apache.storm.daemon.drpc.DRPC", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test03()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      DRPC dRPC0 = new DRPC(stormMetricsRegistry0, (IAuthorizer) null, 689L);
//      // Undeclared exception!
//      try {
//        dRPC0.returnResult((String) null, (String) null);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test04()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      SimpleWhitelistAuthorizer simpleWhitelistAuthorizer0 = new SimpleWhitelistAuthorizer();
//      DRPC dRPC0 = new DRPC(stormMetricsRegistry0, simpleWhitelistAuthorizer0, 2L);
//      DRPCExecutionException dRPCExecutionException0 = new DRPCExecutionException((String) null);
//      // Undeclared exception!
//      try {
//        dRPC0.failRequest((String) null, dRPCExecutionException0);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test05()  throws Throwable  {
//      DRPC dRPC0 = null;
//      try {
//        dRPC0 = new DRPC((StormMetricsRegistry) null, (IAuthorizer) null, 1L);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.storm.daemon.drpc.DRPC", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test06()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      SupervisorSimpleACLAuthorizer supervisorSimpleACLAuthorizer0 = new SupervisorSimpleACLAuthorizer();
//      DRPC dRPC0 = null;
//      try {
//        dRPC0 = new DRPC(stormMetricsRegistry0, supervisorSimpleACLAuthorizer0, 0L);
//        fail("Expecting exception: IllegalArgumentException");
//
//      } catch(IllegalArgumentException e) {
//         //
//         // Non-positive period.
//         //
//         verifyException("java.util.Timer", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test07()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      stormMetricsRegistry0.registerHistogram("drpc:num-failRequest-calls");
//      DRPC dRPC0 = null;
//      try {
//        dRPC0 = new DRPC(stormMetricsRegistry0, (IAuthorizer) null, 0L);
//        fail("Expecting exception: IllegalArgumentException");
//
//      } catch(IllegalArgumentException e) {
//         //
//         // drpc:num-failRequest-calls is already used for a different type of metric
//         //
//         verifyException("com.codahale.metrics.MetricRegistry", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test08()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      DRPC dRPC0 = null;
//      try {
//        dRPC0 = new DRPC(stormMetricsRegistry0, (Map<String, Object>) null);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.storm.daemon.drpc.DRPC", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test09()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
//      hashMap0.put("drpc.request.timeout.secs", stormMetricsRegistry0);
//      DRPC dRPC0 = null;
//      try {
//        dRPC0 = new DRPC(stormMetricsRegistry0, hashMap0);
//        fail("Expecting exception: IllegalArgumentException");
//
//      } catch(IllegalArgumentException e) {
//         //
//         // Don't know how to convert org.apache.storm.metric.StormMetricsRegistry@2 to int
//         //
//         verifyException("org.apache.storm.utils.ObjectReader", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test10()  throws Throwable  {
//    Future<?> future = executor.submit(new Runnable(){
//            @Override public void run() {
//        try {
//          StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//          ImpersonationAuthorizer impersonationAuthorizer0 = new ImpersonationAuthorizer();
//          DRPC dRPC0 = new DRPC(stormMetricsRegistry0, impersonationAuthorizer0, 4951L);
//          RequestFactory<BlockingOutstandingRequest> requestFactory0 = BlockingOutstandingRequest.FACTORY;
//          // Undeclared exception!
//          try {
//            dRPC0.execute((String) null, "hYU\r127pmNK", requestFactory0);
//            fail("Expecting exception: SecurityException");
//
//          } catch(SecurityException e) {
//             //
//             // Security manager blocks (\"javax.security.auth.AuthPermission\" \"getSubject\")
//             // java.lang.Thread.getStackTrace(Thread.java:1564)
//             // org.evosuite.runtime.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:434)
//             // javax.security.auth.Subject.getSubject(Subject.java:287)
//             // org.apache.storm.security.auth.ReqContext.<init>(ReqContext.java:51)
//             // org.apache.storm.security.auth.ReqContext.lambda$static$0(ReqContext.java:42)
//             // java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
//             // java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
//             // java.lang.ThreadLocal.get(ThreadLocal.java:172)
//             // org.apache.storm.security.auth.ReqContext.context(ReqContext.java:78)
//             // org.apache.storm.daemon.drpc.DRPC.checkAuthorization(DRPC.java:139)
//             // org.apache.storm.daemon.drpc.DRPC.execute(DRPC.java:221)
//             // sun.reflect.GeneratedMethodAccessor147.invoke(Unknown Source)
//             // sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
//             // java.lang.reflect.Method.invoke(Method.java:498)
//             // org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:257)
//             // org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169)
//             // org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:220)
//             // org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307)
//             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213)
//             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55)
//             // java.util.concurrent.FutureTask.run(FutureTask.java:266)
//             // java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
//             // java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
//             // java.lang.Thread.run(Thread.java:750)
//             //
//             verifyException("org.evosuite.runtime.sandbox.MSecurityManager", e);
//          }
//        } catch(Throwable t) {
//            // Need to catch declared exceptions
//        }
//      }
//    });
//    future.get(4000, TimeUnit.MILLISECONDS);
//  }
//
//  @Test(timeout = 4000)
//  public void test11()  throws Throwable  {
//      DenyAuthorizer denyAuthorizer0 = new DenyAuthorizer();
//      LinkedHashSet<JMXPrincipal> linkedHashSet0 = new LinkedHashSet<JMXPrincipal>();
//      JMXPrincipal jMXPrincipal0 = new JMXPrincipal("9k1G");
//      linkedHashSet0.add(jMXPrincipal0);
//      Subject subject0 = new Subject(true, linkedHashSet0, linkedHashSet0, linkedHashSet0);
//      ReqContext reqContext0 = new ReqContext(subject0);
//      try {
//        DRPC.checkAuthorization(reqContext0, denyAuthorizer0, "9k1G", "9k1G");
//        fail("Expecting exception: Exception");
//
//      } catch(Exception e) {
//         //
//         // DRPC request '9k1G' for '9k1G' user is not authorized
//         //
//         verifyException("org.apache.storm.daemon.drpc.DRPC", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test12()  throws Throwable  {
//      ReqContext reqContext0 = new ReqContext((Subject) null);
//      NoopAuthorizer noopAuthorizer0 = new NoopAuthorizer();
//      DRPC.checkAuthorization(reqContext0, noopAuthorizer0, (String) null, (String) null);
//      //  // Unstable assertion: assertEquals(15, reqContext0.requestID());
//  }
//
//  @Test(timeout = 4000)
//  public void test13()  throws Throwable  {
//      ImpersonationAuthorizer impersonationAuthorizer0 = new ImpersonationAuthorizer();
//      // Undeclared exception!
//      try {
//        DRPC.checkAuthorization((ReqContext) null, impersonationAuthorizer0, "wfisS0(:da4(}5", "wfisS0(:da4(}5");
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.storm.security.auth.authorizer.ImpersonationAuthorizer", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test14()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
//      DRPC dRPC0 = new DRPC(stormMetricsRegistry0, hashMap0);
//      dRPC0.close();
//  }
//
//  @Test(timeout = 4000)
//  public void test15()  throws Throwable  {
//      Subject subject0 = new Subject();
//      ReqContext reqContext0 = new ReqContext(subject0);
//      DRPC.checkAuthorization(reqContext0, (IAuthorizer) null, "org.apache.storm.pacemaker.PacemakerConnectionException", "org.apache.storm.pacemaker.PacemakerConnectionException");
//      assertEquals(1, reqContext0.requestID());
//  }
//
//  @Test(timeout = 4000)
//  public void test16()  throws Throwable  {
//    Future<?> future = executor.submit(new Runnable(){
//            @Override public void run() {
//        try {
//          StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//          DRPCSimpleACLAuthorizer dRPCSimpleACLAuthorizer0 = new DRPCSimpleACLAuthorizer();
//          DRPC dRPC0 = new DRPC(stormMetricsRegistry0, dRPCSimpleACLAuthorizer0, 3899L);
//          // Undeclared exception!
//          try {
//            dRPC0.fetchRequest("function.name");
//            fail("Expecting exception: SecurityException");
//
//          } catch(SecurityException e) {
//             //
//             // Security manager blocks (\"javax.security.auth.AuthPermission\" \"getSubject\")
//             // java.lang.Thread.getStackTrace(Thread.java:1564)
//             // org.evosuite.runtime.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:434)
//             // javax.security.auth.Subject.getSubject(Subject.java:287)
//             // org.apache.storm.security.auth.ReqContext.<init>(ReqContext.java:51)
//             // org.apache.storm.security.auth.ReqContext.lambda$static$0(ReqContext.java:42)
//             // java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
//             // java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
//             // java.lang.ThreadLocal.get(ThreadLocal.java:172)
//             // org.apache.storm.security.auth.ReqContext.context(ReqContext.java:78)
//             // org.apache.storm.daemon.drpc.DRPC.checkAuthorizationNoLog(DRPC.java:143)
//             // org.apache.storm.daemon.drpc.DRPC.fetchRequest(DRPC.java:192)
//             // sun.reflect.GeneratedMethodAccessor139.invoke(Unknown Source)
//             // sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
//             // java.lang.reflect.Method.invoke(Method.java:498)
//             // org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:257)
//             // org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169)
//             // org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:220)
//             // org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307)
//             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213)
//             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55)
//             // java.util.concurrent.FutureTask.run(FutureTask.java:266)
//             // java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
//             // java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
//             // java.lang.Thread.run(Thread.java:750)
//             //
//             verifyException("org.evosuite.runtime.sandbox.MSecurityManager", e);
//          }
//        } catch(Throwable t) {
//            // Need to catch declared exceptions
//        }
//      }
//    });
//    future.get(4000, TimeUnit.MILLISECONDS);
//  }
//
//  @Test(timeout = 4000)
//  public void test17()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      DRPC dRPC0 = new DRPC(stormMetricsRegistry0, (IAuthorizer) null, 689L);
//      DRPCExecutionException dRPCExecutionException0 = new DRPCExecutionException("org.apache.storm.pacemaker.PacemakerConnectionException");
//      dRPC0.failRequest("org.apache.storm.pacemaker.PacemakerConnectionException", dRPCExecutionException0);
//      assertEquals("org.apache.storm.pacemaker.PacemakerConnectionException", dRPCExecutionException0.get_msg());
//  }
//}
