///*
// * This file was automatically generated by EvoSuite
// * Mon Jul 13 16:18:22 GMT 2026
// */
//
//package org.apache.storm.daemon.drpc_3.another.evosuite;
//
//import org.apache.storm.daemon.drpc.BlockingOutstandingRequest;
//import org.apache.storm.daemon.drpc.DRPC;
//import org.apache.storm.daemon.drpc.RequestFactory;
//import org.apache.storm.generated.DRPCExecutionException;
//import org.apache.storm.metric.StormMetricsRegistry;
//import org.apache.storm.security.auth.IAuthorizer;
//import org.apache.storm.security.auth.ReqContext;
//import org.apache.storm.security.auth.authorizer.*;
//import org.evosuite.runtime.EvoRunner;
//import org.evosuite.runtime.EvoRunnerParameters;
//import org.evosuite.runtime.System;
//import org.junit.Test;
//import org.junit.runner.RunWith;
//import org.slf4j.Logger;
//import org.slf4j.event.EventRecodingLogger;
//import org.slf4j.event.SubstituteLoggingEvent;
//import org.slf4j.helpers.SubstituteLogger;
//
//import javax.security.auth.Subject;
//import java.util.HashMap;
//import java.util.LinkedList;
//import java.util.Map;
//import java.util.concurrent.Future;
//import java.util.concurrent.TimeUnit;
//
//import static org.evosuite.runtime.EvoAssertions.*;
//import static org.junit.Assert.assertEquals;
//import static org.junit.Assert.fail;
//
//@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true)
//public class DRPC_ESTest extends DRPC_ESTest_scaffolding {
//
//  @Test(timeout = 4000)
//  public void test00()  throws Throwable  {
//    Future<?> future = executor.submit(new Runnable(){
//            @Override public void run() {
//        try {
//          StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//          HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
//          DRPC dRPC0 = new DRPC(stormMetricsRegistry0, hashMap0);
//          // Undeclared exception!
//          try {
//            dRPC0.fetchRequest("org.apace.storm.daemn.;rpc.DRPC$1");
//            fail("Expecting exception: SecurityException");
//
//          } catch(SecurityException e) {
//             //
//             // Security manager blocks (\"javax.security.auth.AuthPermission\" \"getSubject\")
//             // java.lang.Thread.getStackTrace(Thread.java:1564)
//             // org.evosuite.runtime.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:434)
//             // javax.security.auth.Subject.getSubject(Subject.java:287)
//             // org.apache.storm.security.auth.ReqContext.<init>(ReqContext.java:51)
//             // org.apache.storm.security.auth.ReqContext.lambda$static$0(ReqContext.java:42)
//             // java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
//             // java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
//             // java.lang.ThreadLocal.get(ThreadLocal.java:172)
//             // org.apache.storm.security.auth.ReqContext.context(ReqContext.java:78)
//             // org.apache.storm.daemon.drpc.DRPC.fetchRequest(DRPC.java:151)
//             // sun.reflect.GeneratedMethodAccessor205.invoke(Unknown Source)
//             // sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
//             // java.lang.reflect.Method.invoke(Method.java:498)
//             // org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:257)
//             // org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169)
//             // org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:220)
//             // org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307)
//             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213)
//             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55)
//             // java.util.concurrent.FutureTask.run(FutureTask.java:266)
//             // java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
//             // java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
//             // java.lang.Thread.run(Thread.java:750)
//             //
//             verifyException("org.evosuite.runtime.sandbox.MSecurityManager", e);
//          }
//        } catch(Throwable t) {
//            // Need to catch declared exceptions
//        }
//      }
//    });
//    future.get(4000, TimeUnit.MILLISECONDS);
//  }
//
//  @Test(timeout = 4000)
//  public void test01()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
//      DRPC dRPC0 = new DRPC(stormMetricsRegistry0, hashMap0);
//      // Undeclared exception!
//      try {
//        dRPC0.returnResult((String) null, "");
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test02()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      ImpersonationAuthorizer impersonationAuthorizer0 = new ImpersonationAuthorizer();
//      DRPC dRPC0 = new DRPC(stormMetricsRegistry0, impersonationAuthorizer0, 2862933555777941757L);
//      System.setCurrentTimeMillis(2862933555777941757L);
//      // Undeclared exception!
//      dRPC0.fetchRequest("");
//  }
//
//  @Test(timeout = 4000)
//  public void test03()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      ImpersonationAuthorizer impersonationAuthorizer0 = new ImpersonationAuthorizer();
//      DRPC dRPC0 = new DRPC(stormMetricsRegistry0, impersonationAuthorizer0, 2862933555777941757L);
//      System.setCurrentTimeMillis(2862933555777941757L);
//      // Undeclared exception!
//      dRPC0.executeBlocking("$1BE#wN?b%f_`J@", "$1BE#wN?b%f_`J@");
//  }
//
//  @Test(timeout = 4000)
//  public void test04()  throws Throwable  {
//      Subject subject0 = new Subject();
//      ReqContext reqContext0 = new ReqContext(subject0);
//      DRPCSimpleACLAuthorizer dRPCSimpleACLAuthorizer0 = new DRPCSimpleACLAuthorizer();
//      // Undeclared exception!
//      try {
//        DRPC.checkAuthorization(reqContext0, (IAuthorizer) dRPCSimpleACLAuthorizer0, "failRequest", "invocation.user", dRPCSimpleACLAuthorizer0.LOG);
//        fail("Expecting exception: RuntimeException");
//
//      } catch(RuntimeException e) {
//         //
//         // org.evosuite.runtime.mock.java.lang.MockThrowable: Found multiple  resources. You're probably bundling the Storm jars with your topology jar. [file:/C:/Users/valba/OneDrive/Desktop/PROGETTO%20ISPW2/DEANGELIS/storm-2.5.0/storm-client/target/classes/, file:/C:/Users/valba/OneDrive/Desktop/PROGETTO%20ISPW2/DEANGELIS/storm-2.5.0/storm-server/target/classes/]
//         //
//         verifyException("org.apache.storm.utils.Utils", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test05()  throws Throwable  {
//      DenyAuthorizer denyAuthorizer0 = new DenyAuthorizer();
//      LinkedList<SubstituteLoggingEvent> linkedList0 = new LinkedList<SubstituteLoggingEvent>();
//      SubstituteLogger substituteLogger0 = new SubstituteLogger("6W9S(", linkedList0, true);
//      EventRecodingLogger eventRecodingLogger0 = new EventRecodingLogger(substituteLogger0, linkedList0);
//      // Undeclared exception!
//      try {
//        DRPC.checkAuthorization((ReqContext) null, (IAuthorizer) denyAuthorizer0, "createContainer", "6W9S(", (Logger) eventRecodingLogger0);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.storm.daemon.drpc.DRPC", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test06()  throws Throwable  {
//      ImpersonationAuthorizer impersonationAuthorizer0 = new ImpersonationAuthorizer();
//      // Undeclared exception!
//      try {
//        DRPC.checkAuthorization((ReqContext) null, impersonationAuthorizer0, "", "unknown");
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.storm.security.auth.authorizer.ImpersonationAuthorizer", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test07()  throws Throwable  {
//      SupervisorSimpleACLAuthorizer supervisorSimpleACLAuthorizer0 = new SupervisorSimpleACLAuthorizer();
//      DRPC dRPC0 = null;
//      try {
//        dRPC0 = new DRPC((StormMetricsRegistry) null, supervisorSimpleACLAuthorizer0, 0L);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.storm.daemon.drpc.DRPC", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test08()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      stormMetricsRegistry0.registerHistogram("drpc:num-server-timed-out-requests");
//      DRPC dRPC0 = null;
//      try {
//        dRPC0 = new DRPC(stormMetricsRegistry0, (IAuthorizer) null, 0L);
//        fail("Expecting exception: IllegalArgumentException");
//
//      } catch(IllegalArgumentException e) {
//         //
//         // drpc:num-server-timed-out-requests is already used for a different type of metric
//         //
//         verifyException("com.codahale.metrics.MetricRegistry", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test09()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      DRPC dRPC0 = null;
//      try {
//        dRPC0 = new DRPC(stormMetricsRegistry0, (Map<String, Object>) null);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.storm.daemon.drpc.DRPC", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test10()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      stormMetricsRegistry0.registerTimer("drpc:num-failRequest-calls");
//      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
//      DRPC dRPC0 = null;
//      try {
//        dRPC0 = new DRPC(stormMetricsRegistry0, hashMap0);
//        fail("Expecting exception: IllegalArgumentException");
//
//      } catch(IllegalArgumentException e) {
//         //
//         // drpc:num-failRequest-calls is already used for a different type of metric
//         //
//         verifyException("com.codahale.metrics.MetricRegistry", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test11()  throws Throwable  {
//      Subject subject0 = new Subject();
//      ReqContext reqContext0 = new ReqContext(subject0);
//      NoopAuthorizer noopAuthorizer0 = new NoopAuthorizer();
////      ch.qos.logback.classic.Logger logger0 = (ch.qos.logback.classic.Logger)DRPCSimpleACLAuthorizer.LOG;
////      DRPC.checkAuthorization(reqContext0, (IAuthorizer) noopAuthorizer0, "hOH=HwS,Kn", "=;Ylng4;", (Logger) logger0);
//      //  // Unstable assertion: assertEquals(59, reqContext0.requestID());
//  }
//
//  @Test(timeout = 4000)
//  public void test12()  throws Throwable  {
//      DRPCSimpleACLAuthorizer dRPCSimpleACLAuthorizer0 = new DRPCSimpleACLAuthorizer();
//      ReqContext reqContext0 = new ReqContext((Subject) null);
//      try {
//        DRPC.checkAuthorization(reqContext0, (IAuthorizer) dRPCSimpleACLAuthorizer0, "invocation.user", "invocation.user", dRPCSimpleACLAuthorizer0.LOG);
//        fail("Expecting exception: Exception");
//
//      } catch(Exception e) {
//         //
//         // DRPC request is not authorized
//         //
//         verifyException("org.apache.storm.daemon.drpc.DRPC", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test13()  throws Throwable  {
//      LinkedList<SubstituteLoggingEvent> linkedList0 = new LinkedList<SubstituteLoggingEvent>();
//      SubstituteLogger substituteLogger0 = new SubstituteLogger("V6pl+k*\"cll^jg", linkedList0, false);
//      EventRecodingLogger eventRecodingLogger0 = new EventRecodingLogger(substituteLogger0, linkedList0);
//      DRPC.checkAuthorization((ReqContext) null, (IAuthorizer) null, "", "org.apache.storm.generated.WorkerToken$WorkerTokenTupleSchemeFactory", (Logger) eventRecodingLogger0);
//  }
//
//  @Test(timeout = 4000)
//  public void test14()  throws Throwable  {
//    Future<?> future = executor.submit(new Runnable(){
//            @Override public void run() {
//        try {
//          StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//          ImpersonationAuthorizer impersonationAuthorizer0 = new ImpersonationAuthorizer();
//          DRPC dRPC0 = new DRPC(stormMetricsRegistry0, impersonationAuthorizer0, (-1L));
//          RequestFactory<BlockingOutstandingRequest> requestFactory0 = BlockingOutstandingRequest.FACTORY;
//          // Undeclared exception!
//          try {
//            dRPC0.execute("drpc-request-cleanup", "drpc-request-cleanup", requestFactory0);
//            fail("Expecting exception: SecurityException");
//
//          } catch(SecurityException e) {
//             //
//             // Security manager blocks (\"javax.security.auth.AuthPermission\" \"getSubject\")
//             // java.lang.Thread.getStackTrace(Thread.java:1564)
//             // org.evosuite.runtime.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:434)
//             // javax.security.auth.Subject.getSubject(Subject.java:287)
//             // org.apache.storm.security.auth.ReqContext.<init>(ReqContext.java:51)
//             // org.apache.storm.security.auth.ReqContext.lambda$static$0(ReqContext.java:42)
//             // java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
//             // java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
//             // java.lang.ThreadLocal.get(ThreadLocal.java:172)
//             // org.apache.storm.security.auth.ReqContext.context(ReqContext.java:78)
//             // org.apache.storm.daemon.drpc.DRPC.execute(DRPC.java:195)
//             // sun.reflect.GeneratedMethodAccessor201.invoke(Unknown Source)
//             // sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
//             // java.lang.reflect.Method.invoke(Method.java:498)
//             // org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:257)
//             // org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169)
//             // org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:220)
//             // org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307)
//             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213)
//             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55)
//             // java.util.concurrent.FutureTask.run(FutureTask.java:266)
//             // java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
//             // java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
//             // java.lang.Thread.run(Thread.java:750)
//             //
//             verifyException("org.evosuite.runtime.sandbox.MSecurityManager", e);
//          }
//        } catch(Throwable t) {
//            // Need to catch declared exceptions
//        }
//      }
//    });
//    future.get(4000, TimeUnit.MILLISECONDS);
//  }
//
//  @Test(timeout = 4000)
//  public void test15()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
//      DRPC dRPC0 = new DRPC(stormMetricsRegistry0, hashMap0);
//      dRPC0.close();
//  }
//
//  @Test(timeout = 4000)
//  public void test16()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
//      DRPC dRPC0 = new DRPC(stormMetricsRegistry0, hashMap0);
//      DRPCExecutionException dRPCExecutionException0 = new DRPCExecutionException("org.apace.storm.daemn.;rpc.DRPC$1");
//      dRPC0.failRequest("org.apace.storm.daemn.;rpc.DRPC$1", dRPCExecutionException0);
//      assertEquals("org.apace.storm.daemn.;rpc.DRPC$1", dRPCExecutionException0.get_msg());
//  }
//
//  @Test(timeout = 4000)
//  public void test17()  throws Throwable  {
//      DRPCSimpleACLAuthorizer dRPCSimpleACLAuthorizer0 = new DRPCSimpleACLAuthorizer();
//      ReqContext reqContext0 = new ReqContext((Subject) null);
//      try {
//        DRPC.checkAuthorization(reqContext0, dRPCSimpleACLAuthorizer0, "function.name", "function.name");
//        fail("Expecting exception: Exception");
//
//      } catch(Exception e) {
//         //
//         // DRPC request is not authorized
//         //
//         verifyException("org.apache.storm.daemon.drpc.DRPC", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test18()  throws Throwable  {
//      ReqContext reqContext0 = new ReqContext((Subject) null);
//      DRPC.checkAuthorization(reqContext0, (IAuthorizer) null, "f", (String) null);
//      assertEquals(1, reqContext0.requestID());
//  }
//
//  @Test(timeout = 4000)
//  public void test19()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
//      hashMap0.put("drpc.authorizer", stormMetricsRegistry0);
//      DRPC dRPC0 = null;
//      try {
//        dRPC0 = new DRPC(stormMetricsRegistry0, hashMap0);
//        fail("Expecting exception: IllegalStateException");
//
//      } catch(IllegalStateException e) {
//         //
//         // Unable to instantiate DRPC authorizer org.apache.storm.metric.StormMetricsRegistry@2
//         //
//         verifyException("org.apache.storm.daemon.drpc.DRPC", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test20()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
//      DRPC dRPC0 = new DRPC(stormMetricsRegistry0, hashMap0);
//      dRPC0.returnResult("org.apace.storm.daemn.;rpc.DRPC$1", "org.apace.storm.daemn.;rpc.DRPC$1");
//  }
//
//  @Test(timeout = 4000)
//  public void test21()  throws Throwable  {
//    Future<?> future = executor.submit(new Runnable(){
//            @Override public void run() {
//        try {
//          StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//          DRPCSimpleACLAuthorizer dRPCSimpleACLAuthorizer0 = new DRPCSimpleACLAuthorizer();
//          DRPC dRPC0 = new DRPC(stormMetricsRegistry0, dRPCSimpleACLAuthorizer0, (-853L));
//          // Undeclared exception!
//          try {
//            dRPC0.executeBlocking("invocation.user", "client.users");
//            fail("Expecting exception: SecurityException");
//
//          } catch(SecurityException e) {
//             //
//             // Security manager blocks (\"javax.security.auth.AuthPermission\" \"getSubject\")
//             // java.lang.Thread.getStackTrace(Thread.java:1564)
//             // org.evosuite.runtime.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:434)
//             // javax.security.auth.Subject.getSubject(Subject.java:287)
//             // org.apache.storm.security.auth.ReqContext.<init>(ReqContext.java:51)
//             // org.apache.storm.security.auth.ReqContext.lambda$static$0(ReqContext.java:42)
//             // java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
//             // java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
//             // java.lang.ThreadLocal.get(ThreadLocal.java:172)
//             // org.apache.storm.security.auth.ReqContext.context(ReqContext.java:78)
//             // org.apache.storm.daemon.drpc.DRPC.execute(DRPC.java:195)
//             // org.apache.storm.daemon.drpc.DRPC.executeBlocking(DRPC.java:207)
//             // sun.reflect.GeneratedMethodAccessor190.invoke(Unknown Source)
//             // sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
//             // java.lang.reflect.Method.invoke(Method.java:498)
//             // org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:257)
//             // org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169)
//             // org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:220)
//             // org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307)
//             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213)
//             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55)
//             // java.util.concurrent.FutureTask.run(FutureTask.java:266)
//             // java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
//             // java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
//             // java.lang.Thread.run(Thread.java:750)
//             //
//             verifyException("org.evosuite.runtime.sandbox.MSecurityManager", e);
//          }
//        } catch(Throwable t) {
//            // Need to catch declared exceptions
//        }
//      }
//    });
//    future.get(4000, TimeUnit.MILLISECONDS);
//  }
//
//  @Test(timeout = 4000)
//  public void test22()  throws Throwable  {
//      StormMetricsRegistry stormMetricsRegistry0 = new StormMetricsRegistry();
//      DRPCSimpleACLAuthorizer dRPCSimpleACLAuthorizer0 = new DRPCSimpleACLAuthorizer();
//      DRPC dRPC0 = new DRPC(stormMetricsRegistry0, dRPCSimpleACLAuthorizer0, 0L);
//      DRPCExecutionException dRPCExecutionException0 = new DRPCExecutionException();
//      // Undeclared exception!
//      try {
//        dRPC0.failRequest((String) null, dRPCExecutionException0);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//      }
//  }
//}
